### ISSUE TITLE
Analytics error on Android

### ISSUE THREAD

**Issue by bzytan** [fullstackreact/react-native-firestack#100]
I managed to get the firebase analytics working for iOS. Great stuff! However on Android, when I call the following

import Firestack from 'react-native-firestack'

componentWillMount() {
	var firestack = new Firestack();
	firestack.analytics.logEventWithName("view_screen", {
	  'screen': 'Now Showing'
	})
	.then(res => console.log('Sent event named view_screen'))
	.catch(err => console.error('Firebase Analytics Error: ' + err));
  }

I'm getting the following error. Anyone else experienced this?

undefined is not an object (evaluating 'NativeModule[fn]')

<img width="377" alt="screenshot 2016-10-31 21 00 09" src="https://cloud.githubusercontent.com/assets/2832933/19855068/7cdb2746-9fad-11e6-8bae-bc4891565f66.png">

**Comment by auser** [comment]
Did you run `react-native link react-native-firestack` ?
