### ISSUE TITLE
Firestack Storage Error: location must not be null or empty

### ISSUE THREAD

**Issue by eliyazdi** [fullstackreact/react-native-firestack#105]
Hi!

I just started using Firestack today, and everything seems to be working pretty well (database, auth, etc), but I am running into some errors when using storage. I implemented something similar to the example given in the README with react-native-camera. Here is my code:
![screen shot 2016-11-01 at 19 30 01](https://cloud.githubusercontent.com/assets/1785818/19911450/ff44c82e-a069-11e6-998c-cdb4a5db87a7.png)
when the uri console logs, it gives a perfectly valid location for where the image is stored on the phone (example - file:///data/user/0/com.spotted/cache/IMG_20161101_1816371492148263.jpg). However, when I try to upload that image, I get the following error:
![screenshot_20161101-192618](https://cloud.githubusercontent.com/assets/1785818/19911524/8116a6d8-a06a-11e6-95f2-841ed444bde2.png)

I have also tried manually putting in locations of various images on my phone, and it always gives the same error. Any idea why it might be doing this?

Thanks!

**Comment by eliyazdi** [comment]
As it turns out, I was just forgetting to set the storage bucket.

Thanks, this module works really well :)

**Comment by morelazers** [comment]
Hi @eliyazdi, I'm having the same error on Android.

I've added the `google-services.json`, and I'm setting up the new Firestack instance like this:
```
const configurationOptions = {
  debug: true,
  databaseURL: "https://catsignal-96224.firebaseio.com",
  storageBucket: "catsignal-96224.appspot.com"
};
const firestack = new Firestack(configurationOptions);
```

But if I log the Firestack instance later on (like when I try to upload something to storage), I can see that `configured: false`.

To clarify, I'm doing the above in my root component, then in another component I am doing `let firestack = new Firestack()` to get the singleton.

Are you able to provide any insight?
