### ISSUE TITLE
[v3] sendEmailVerification is not supported

### ISSUE THREAD

**Issue by ghuh** [fullstackreact/react-native-firestack#114]
When a new email/password user is created, in order to verify their email, need to send a verification email.  Firebase has built in support for this which needs to be exposed in firestack.  

Android: https://firebase.google.com/docs/auth/android/manage-users#send_a_user_a_verification_email

iOS: https://firebase.google.com/docs/auth/ios/manage-users#send_a_user_a_verification_email

Web: https://firebase.google.com/docs/auth/web/manage-users#send_a_user_a_verification_email

**Comment by Salakar** [comment]
@ghuh this is implemented on my branch now (the soon to be v3) and you can also now access the current users email verification status by doing:

```javascript
const user = firestack.auth().currentUser;

if (user) {
    if (!user.emailVerified) {
        console.warn(`User ${user.uid} is not verified`);
    }  else {
        // resend verification email? or w/e else you'd do in this scenario
        user.sendEmailVerification(); 
    }
} else {
    // not signed in
}
```

Feel free to give it ago - we'll be merging this in soon hopefully.

**Comment by ghuh** [comment]
Thanks!  I'll take a look.

**Comment by Salakar** [comment]
Closing as fixed on v3 branch.
