### ISSUE TITLE
Auth getToken is not refreshing expired token on iOS

### ISSUE THREAD

**Issue by ghuh** [fullstackreact/react-native-firestack#116]
Calling getToken should refresh expired tokens on iOS but it keeps returning the same expired token.  I have not tried it yet on Android so I don't know if this is iOS only.

**Comment by auser** [comment]
Thanks for the report. Is this with the `npm` module or master branch?

**Comment by ghuh** [comment]
This is v2.3.3 from npm.

**Comment by ghuh** [comment]
This appears to be working correctly on Android.

**Comment by auser** [comment]
I think I know the issue. I'll look at it shortly though. Can you make a demo screen in FirestackApp?
I'll update the readme on how to handle it, if so. They basically are just view screens

Get Outlook for iOS




On Mon, Nov 7, 2016 at 7:22 PM -0800, "ghuh" <notifications@github.com> wrote:












This appears to be working correctly on Android.

**Comment by ghuh** [comment]
Note that I deleted the comment about it working in Android because my test was invalid. I retested and confirmed that it is broken on Android as well.

**Comment by auser** [comment]
Interesting... can you share how you're testing it so we're working off the same baseline?

**Comment by ghuh** [comment]
I'm testing using code baked into a much larger app that will take some time to split out.  Are you not seeing the same results?

**Comment by auser** [comment]
No, I haven't seen this myself. If you have screenhero, I'm glad to hop on and help debug, if you can't share it.

**Comment by ghuh** [comment]
I haven't had a chance to debug this yet.  Hopefully I can tackle that this evening.  I'll let you know if I'm having any issues.

If you have an idea of what might be the issue to point me in the right direction before I get started, let me know.

**Comment by ghuh** [comment]
Well this turned out to be user error.  getToken is refreshing the token.

It is worth noting that the behavior of iOS and Android are different.  iOS will only refresh the token if it is expired and Android will force refresh every time.  Both platforms ignore the force refresh boolean from the JS documentation.
