### ISSUE TITLE
[v3] Auth Module: Bring methods in-line & add missing methods

### ISSUE THREAD

**Issue by Ehesp** [fullstackreact/react-native-firestack#118]
Currently working through the auth docs on my own fork, there's some differences between the Firestack methods vs the JS method names.  I believe it should mimic the Firebase API as close as possible, since most users will reference their docs on how to do certain things, it'd make it easy to come straight to the same method here.

Also some methods are missing:

### Differences:
- [x] listenForAuth
  - [onAuthStateChanged](https://firebase.google.com/docs/reference/js/firebase.auth.Auth#onAuthStateChanged)
  - Might also be worth renaming `unlistenForAuth` to `removeOnAuthStateChanged` or something?
- [x] createUserWithEmail
  - [createUserWithEmailAndPassword](https://firebase.google.com/docs/reference/js/firebase.auth.Auth#createUserWithEmailAndPassword)
- [x] signInWithEmail
  - [signInWithEmailAndPassword](https://firebase.google.com/docs/reference/js/firebase.auth.Auth#signInWithEmailAndPassword)
- [x] updateUserEmail
  - [updateEmail](https://firebase.google.com/docs/reference/js/firebase.User#updateEmail)
- [x] updateUserPassword
  - [updatePassword](https://firebase.google.com/docs/reference/js/firebase.User#updatePassword)
- [x] updateUserProfile
  - [updateProfile](https://firebase.google.com/docs/auth/web/manage-users#update_a_users_profile)
- [x] sendPasswordResetWithEmail
  - [sendPasswordResetEmail](https://firebase.google.com/docs/auth/web/manage-users#send_a_password_reset_email)
- [x] deleteUser
  - This is just `user.delete()`, not sure whether `firebase.auth.delete()` would feel correct?

### Missing:
- [x] [sendEmailVerification](https://firebase.google.com/docs/auth/web/manage-users#send_a_user_a_verification_email) (https://github.com/fullstackreact/react-native-firestack/issues/114)

### Not working
- [x] signOut
  - Returns ok but doesn't sign out.
- [x] signIn with disabled account(all?)
  - Crashes the app on boot.

**Comment by auser** [comment]
At this point, I think we need to create a `deprecated` helper that logs out deprecated warnings about using these methods and rename the methods to match their firebase js counterparts. Want to take a crack at that?

**Comment by Ehesp** [comment]
Sure, would a `console.warn` suffice?

**Comment by auser** [comment]
Yep, definitely would.
