### ISSUE TITLE
Facebook Auth

### ISSUE THREAD

**Issue by DVassilev** [fullstackreact/react-native-firestack#12]
When you mention that facebook oauth is not fully implemented, what do you mean exactly? Also are there any plans on extending this to make use of all firebase features? 

Thanks!

**Comment by auser** [comment]
@DVassilev yep! It is intended on covering all the features of Firebase (as much as possible) and Facebook OAuth isn't fully implemented in that it's not built-in and there is some trickiness around setting it up within the library itself. 

It's definitely a priority, though

**Comment by DVassilev** [comment]
@auser oh ok so Facebook currently not functional. Great project though, very handy! I'll try it out soon - do you take donations? Would love to support the further development of this if it proves useful

**Comment by auser** [comment]
Not yet... hopefully I can get it finished shortly. Feel free to contribute to the project, if you'd like as well. Donations? Yeah, that's a good idea... Perhaps I should put that up.

I also just worked with @praneybehl to get the README simpler, so hopefully it's a seamless experience for you.

**Comment by DVassilev** [comment]
Definitely, I'll try to contrivute but at the very least if we use this would be happy to donate. Also it was quite difficult to find this repo, I kept searching for react native firebase and this was far from the first results so I had to go through quite a lot of other outdated ones to get to this which seems to be by far the best.

**Comment by auser** [comment]
Oh shoot... we should fix that... I'm working on a blog post series to get more details/docs out there. 

Feel free to share/tweet about it.

**Comment by DVassilev** [comment]
@auser does this work with https://github.com/fullstackreact/react-native-firestack ? I'm getting the following error when I try to use GeoFire with database through firestack.

`Unhandled JS Exception: Invalid GeoFire location '[object Object]': location must be an array`

**Comment by auser** [comment]
Ah just saw this. The child method should be really easy to add. I'll update the library with it shortly. 

As far as the orderByChild, it should also be straightforward. If you're interested in contributing, I can walk you through it. I can also update it instead.

**Comment by auser** [comment]
I've added the `child()` method to the JS. Will need to update the native sides to use the `orderBy...` functions. I will handle that this holiday weekend.

As far as bit-code goes, It's tough to include for some dependencies (I forget the specifics this minute) required it to be turned off. I can try that again this weekend. (I agree, bitcode would be nice)

**Comment by DVassilev** [comment]
@auser thanks for adding child. I'd be happy to give it a go (adding orderBy) if you can guide me through it (never worked with RN and native modules before though). Had to fall back to the JS firebase library to use it with GeoFire until this has that function. As for bitcode, I suppose it's not really a priority just something down the track you could consider.

**Comment by auser** [comment]
Yes, I'll investigate bit-code this weekend. 

I'll be back at a keyboard tonight and would be happy to walk you through the library and how to add it. 

I haven't investigated geofire yet. Perhaps when we walk through it, we can try it with the library. 

I'm on gchat at: ari@fullstack.io. Feel free to add me and I'll hit you up when I return.

**Comment by DVassilev** [comment]
@auser Do you mind if we use this repo's gitter? I don't have gchat

**Comment by auser** [comment]
I don't mind. I'll be back shortly!

**Comment by auser** [comment]
@DVassilev I am in the gitter channel. Ping me if you'd like to discuss

**Comment by saleeh93** [comment]
#23 Check it out

**Comment by auser** [comment]
@saleeh93 Awesome! Great catch!

**Comment by saleeh93** [comment]
@auser there was some more issues there and npm is not with latest version of git code

**Comment by auser** [comment]
@saleeh93 yes, I haven't released a new npm version. Perhaps now is a good time. 

I am working on an example app so we can get some automated testing baked in. I'm confident it's working right here. Will cut a new release.

**Comment by alexkendall** [comment]
Facebook Auth has been working for me for a while if anyone is wondering.

**Comment by Talkwondo** [comment]
Hello @alexkendall can you share your code? 
i want to make a login from facebook to sign up in firebase also in the database with a unique uid.

**Comment by auser** [comment]
Yes, this is resolved. Especially with `react-native-oauth` :)
