### ISSUE TITLE
snapshot.forEach()

### ISSUE THREAD

**Issue by funkysoul** [fullstackreact/react-native-firestack#125]
I'm not sure if this has been documented somewhere but I'm trying to get iterate through the snapshot children, according to the firebase documentation I would just need to forEach the resulting snapshot. 

`itemsRef.once('value').then(function(snap){
          snap.forEach(function(childSnapshot){
            items.push({
              lastName: childSnapshot.val().last_name,
              firstName: childSnapshot.val().first_name,
              photo: childSnapshot.val().photo,
              nickName: childSnapshot.val().nickname,
              _key: childSnapshot.key
            });
          });
        });`

I'm not sure now if the forEach function has not been implemented or if there is another way to do this properly.

<img width="375" alt="screen shot 2016-11-11 at 10 18 25" src="https://cloud.githubusercontent.com/assets/315914/20210131/30f96ccc-a7f8-11e6-8692-3e61890b8472.png">

**Comment by auser** [comment]
It has been implemented on the `master` branch. It is not yet in the `npm` module.

**Comment by funkysoul** [comment]
Thanks for your quick reply Ari, much appreciated, I've switched to the master branch, had to install bows and es6-symbol packages, installing those packages breaks my application completely.
