### ISSUE TITLE
Documentation overhaul

### ISSUE THREAD

**Issue by Ehesp** [fullstackreact/react-native-firestack#129]
Currently the docs are quite hard to navigate, and the README is quite overwhelming imo. I've started breaking the docs out here:

https://github.com/Ehesp/react-native-firestack

I'll work it in-line with the changes @Salakar is working on (https://github.com/fullstackreact/react-native-firestack/issues/118), starting with Authentication.

**Comment by auser** [comment]
This is great! Let me know when I can pull and check out a PR.

**Comment by Ehesp** [comment]
Now being worked on in v3 branch.
