### ISSUE TITLE
Add googleAuth login

### ISSUE THREAD

**Issue by auser** [fullstackreact/react-native-firestack#13]
Feature to add googleAuth example/update API to include it through `FirestackAuth`

**Comment by prescottprue** [comment]
Looking into adding this as a way to dive into Contributing to the library.

**Comment by auser** [comment]
Awesome @prescottprue. Let me know if you want some assistance. It should be pretty straight-forward, but I'd love to get your thoughts about it if it's confusing.

**Comment by auser** [comment]
Completed. Check with https://github.com/fullstackreact/FirestackApp
