### ISSUE TITLE
Google Signin

### ISSUE THREAD

**Issue by andfs** [fullstackreact/react-native-firestack#130]
I'm not able to signin via Google. I have the accessToken and idToken but when I send to firestack I get an error saying that there are no user:

`firestack.signInWithProvider('google', user.idToken, user.accessToken).then((user)=>{
              console.log(user)
            }).catch((error)=> {
	         console.log(error)
	   });`

result: No user logged in

How may I proceed??

**Comment by chaitanya0bhagvan** [comment]
Before calling `firestack,signInWithProvider` call `firestack.lisenForAuth`. And call to sigInWithProvider should be like this `firestack.signInWithProvider('google', user.idToken)`. Once authentication is complete callback inside `firestack.listenForAuth` will be called with the user.

**Comment by andfs** [comment]
@chaitanya0bhagvan thanks for the response, but it didn't work for me. I'm trying this in the ios simulator. I'll put my code here:
`GoogleSignin.signIn()
      .then((user) => {
        console.log(user);
        const firestack = new Firestack({debug: true});
        firestack.auth.listenForAuth((evt)=> {
			  if (!evt.authenticated) {
			    	console.log(evt.error)
			  } else {
			    console.log('User details', evt.user);
			  }
			  this.setState({user: user, loading: false});
			})
			.then(() => console.log('Listening for authentication changes'))
        firestack.signInWithProvider('google', user.idToken).then((userFirebase)=>{
              console.log(userFirebase)
              this.setState({loading: false, user: userFirebase});
            }).catch((error)=> {
              console.log(error.error)
			       });
        }).catch((err) => {
        console.log('WRONG SIGNIN', err);
      })
      .done();`

In the console I see:

firestack             | [info] Creating new firestack instance
log.js:20 firestack             | [info] Calling configure with options Object {debug: true}
log.js:20 firestack:auth        | [info] Setting up listenForAuth callback
log.js:20 firestack:auth        | [info] Listening for auth...
log.js:20 firestack             | [info] Native configureWithOptions success Object (info in my GoogleService-Info.plist)
login.js:70 Object {error: "No user logged in"}
login.js:81 No user signed in

**Comment by chaitanya0bhagvan** [comment]
@andfs ListenForAuth should be called someplace where you respond to global events. Also check whether you get idToken from google sign in. Sometimes it is null depending on the configuration.

`
const firestack = new Firestack({debug: true}); 
firestack.auth.listenForAuth((evt)=> { 
	if (!evt.authenticated) { console.log(evt.error) } 
	else { console.log('User details', evt.user); this.setState({user: evt.user, loading: false});  } 	
})
.then(() => console.log('Listening for authentication changes')) 

GoogleSignin.signIn().then((user) => 
{ 
	console.log(user); 
	firestack.signInWithProvider('google', user.idToken)
	.then((userFirebase)=>{ console.log(userFirebase) this.setState({loading: false, user: userFirebase.user}); })
	.catch((error)=> { console.log(error.error) }); 
})
.catch((err) => { console.log('WRONG SIGNIN', err); }) 
.done();
`

**Comment by andfs** [comment]
@chaitanya0bhagvan I didn't have success :(

Do you have some example to help me???
Here is my code at the momment that I'm testing some solutions:
https://gist.github.com/andfs/8a5f8c65d21561754b1a6459d7e0ad45

Thanks in advice

**Comment by chaitanya0bhagvan** [comment]
@andfs I used your gist and removed all unrelated code and It just works for me. Take a look at this [GoogleLogin](https://gist.github.com/chaitanya0bhagvan/4439f225d958fbad423349e72ef570da)
. Do add your IOS-ClientID and Web-ClientId

**Comment by andfs** [comment]
Oh crap. I don´t know whats happening. Could it be a domain problem in the Firebase configuration (I added my ios bundle_id there too)? This same code always return "no user logged in" for me. 

Thanks for the help @chaitanya0bhagvan

**Comment by chaitanya0bhagvan** [comment]
@andfs I updated the console statements in this [Gist](https://gist.github.com/chaitanya0bhagvan/4439f225d958fbad423349e72ef570da). Could you take a screen shot of the console log ?

**Comment by auser** [comment]
Please use the `firestack.auth` syntax (https://gist.github.com/auser/87e6a25da0b25c465dd0db097b8864ca#file-firebase_google_login-js-L108)

Sounds like a Firebase configuration issue.

**Comment by andfs** [comment]
@chaitanya0bhagvan @auser thanks for help me. It works \o/

**Comment by birkir** [comment]
There is no idToken in the response unless you use the Google Signin component?
