### ISSUE TITLE
[Android] Don't hard set play services version

### ISSUE THREAD

**Issue by Ehesp** [fullstackreact/react-native-firestack#134]
Hello,

Bear in mind, I'm not to clued up to Android yet...

I keep running into the same issue whereby my build fails due to "Multiple dex files". The cause of this is conflicting play-services versions across multiple libs. This library hard sets the dep to [9.8.0](https://github.com/fullstackreact/react-native-firestack/blob/master/android/build.gradle#L23). 

Other libs seem to only set it to "whatever is latest", e.g: https://github.com/zo0r/react-native-push-notification/blob/master/android/build.gradle#L44 & https://github.com/idehub/react-native-google-analytics-bridge/blob/master/android/build.gradle#L21

The only way I can fix these errors is by either:

1.  Adding this to my own build.gradle:

```
dependencies {
    compile ('com.google.android.gms:play-services-gcm:9.8.0') {
      force = true;
    }
    ...
```

2. Going into node_modules, and changing the [line](https://github.com/fullstackreact/react-native-firestack/blob/master/android/build.gradle#L23) to `compile 'com.google.android.gms:play-services-base:+'`.

Didn't want to make a PR since I'm not sure if this will have any repercussions?

**Comment by auser** [comment]
That should be fine. Make a PR when you get a chance. I think that sounds like a great idea.

**Comment by auser** [comment]
Actually, what do you think about doing this for _all_ Firestack dependencies?

**Comment by Ehesp** [comment]
I supposed the only issue is if the lib isn't kept up to date with say the latest firebase SDK, then users are going to have weird issues.

**Comment by auser** [comment]
Good point. I agree.

**Comment by Salakar** [comment]
Closing as fixed on v3 branch.
