### ISSUE TITLE
Firebase Crash Report

### ISSUE THREAD

**Issue by blumanski** [fullstackreact/react-native-firestack#135]
I get this error a few times in the firebase crash reporting.
The app runs on a new google pixel using
- react-native 0.37.0
- and the newest npm version of firestack
- react-native-facebook-login

**Exception android.os.NetworkOnMainThreadException:**

    android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork (StrictMode.java:1303)
    java.net.SocketOutputStream.socketWrite (SocketOutputStream.java:111)
    java.net.SocketOutputStream.write (SocketOutputStream.java:157)
    okio.Okio$1.write (Okio.java:78)
    okio.AsyncTimeout$1.write (AsyncTimeout.java:180)
    okio.RealBufferedSink.emit (RealBufferedSink.java:178)
    okhttp3.internal.ws.WebSocketWriter.writeControlFrameSynchronized         (WebSocketWriter.java:152)
    okhttp3.internal.ws.WebSocketWriter.writeClose (WebSocketWriter.java:111)
    okhttp3.internal.ws.RealWebSocket.close (RealWebSocket.java:168)
    com.facebook.react.devsupport.JSDebuggerWebSocketClient.closeQuietly     (JSDebuggerWebSocketClient.java:152)
    com.facebook.react.devsupport.WebsocketJavaScriptExecutor$3.run (WebsocketJavaScriptExecutor.java:146)
    android.os.Handler.handleCallback (Handler.java:751)
    android.os.Handler.dispatchMessage (Handler.java:95)
    android.os.Looper.loop (Looper.java:154)
    android.app.ActivityThread.main (ActivityThread.java:6088)
    java.lang.reflect.Method.invoke (Method.java)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:886)
    com.android.internal.os.ZygoteInit.main (ZygoteInit.java:776)

**Comment by auser** [comment]
Yes, that's an issue with the JS Debugger... if you turn off remote debugging, that shouldn't happen. Can you verify that by turning off the remote debugger, @blumanski ?

**Comment by blumanski** [comment]
@auser 
Yes, all good, thanks
