### ISSUE TITLE
iOS uploadFile returns 'Unknown error'

### ISSUE THREAD

**Issue by trajedy** [fullstackreact/react-native-firestack#138]
I'm working on an iOS project with Firestack and have run into an issue whilst trying to upload a file to Firebase Storage.

I have everything setup correctly regarding Firebase and Storage, I have even made my storage permissions completely open as to rule that out as the possible culprit.

```javascript
// Result from ImagePicker (https://github.com/marcshilling/react-native-image-picker)
let source = 'file:///var/mobile/Containers/Data/Application/5C54DB35-262C-4103-969D-C8AED9242A90/Documents/765F9CB5-FDE9-4229-8A26-BF2B011A80BB.jpg'
if (Platform.OS === 'ios') {
  source = source.replace('file://', '')
}
api.uploadPhoto('testing.jpg', source)

...

// Basically straight from the docs
function uploadPhoto (filename, source) {
  return firestack.storage.uploadFile(`images/{$filename}`, source, {
    contentType: 'image/jpeg',
    contentEncoding: 'base64'
  }, (evt) => {
    console.log('Got an event in JS', evt)
  })
  .then((response) => {
    console.log(response)
    return response
  })
  .catch((error) => {
    console.log(error)
    throw error
  })
}
```

**Comment by auser** [comment]
The `FIRStorageErrorCodeUnknown` is what is being returned. Are you using the `npm` or the github version?

**Comment by trajedy** [comment]
I am using yarn/npm, correct that is the error that is being thrown.

The events which occur are

upload_resumed
upload_progress: 0
upload_progress: 0

Then the 'Unknown error' is thrown. There was an error is my previous code

```javascript
firestack.storage.uploadFile(`images/{$filename}`)

// should be

firestack.storage.uploadFile(`images/${filename}`)
```

But the error still persists

**Comment by auser** [comment]
With the same output?

**Comment by trajedy** [comment]
Yes, I tried debugging the iOS code for FirestackStorage.m but C is a little bit beyond me, wanted to see if there was any more context for the error within snapshot.error, but could not work out how to return that with js event.

**Comment by auser** [comment]
Well, just try logging it to the console with to see if this reveals anything new:

```objective-c
NSLog(@"Error: %@", snapshot.error);
```

**Comment by trajedy** [comment]
Ok, I think I'm getting closer, during development I have been deleting user accounts as they are created, the extra context from snapshot.error is suggesting that I'm still interacting with Firebase using an account which no longer exists, even though my storage permissions are set to allow anybody to access that bucket.

```
Error: Error Domain=FIRStorageErrorDomain Code=-13000 "An unknown error occurred, please check the server response." UserInfo={ResponseErrorDomain=FIRStorageErrorDomain, bucket=..., NSLocalizedDescription=An unknown error occurred, please check the server response., error_name=ERROR_USER_NOT_FOUND, object=photos/testing.jpg, ResponseErrorCode=-13020}
```

**Comment by auser** [comment]
Read or write or both?

**Comment by trajedy** [comment]
Both

**Comment by trajedy** [comment]
I will try authenticating with a user account that exists and let you know if the issue persists.

**Comment by auser** [comment]
Okay!

**Comment by trajedy** [comment]
It works! Gah! Can't believe I wasted those hours on such a petty issue. Thank you for your time!

**Comment by auser** [comment]
Np. :) Glad you got it sorted.
