### ISSUE TITLE
Analytics Error

### ISSUE THREAD

**Issue by DVassilev** [fullstackreact/react-native-firestack#14]
Analytics seems to not be functioning correctly. Firebase was added to XCode manually not via Pods.

`<FIRAnalytics/ERROR> Unable to insert bundle. Error: Error Domain=com.google.gmp.measurement.ErrorDomain Code=1 "Failed to insert bundle without App ID" UserInfo={NSLocalizedDescription=Failed to insert bundle without App ID}
<FIRAnalytics/ERROR> Transaction failed`

**Comment by auser** [comment]
Some more detail to this error:

This works on Android. Still investigating iOS

**Comment by auser** [comment]
This is still a bug, but working with the Firebase team to figure this one out.

**Comment by auser** [comment]
Alright, I have confirmation from the Firebase team that this issue is on the Firebase side, not the `react-native-firestack` side. Unfortunately they don't have a timeframe estimate for the fix, but I'll be sure to update this thread as soon as I hear more.

**Comment by auser** [comment]
The latest version of firestack/firebase fixes this bug. YAY!
