### ISSUE TITLE
Storage "upload" method do not save metadata on Android

### ISSUE THREAD

**Issue by Yarikx** [fullstackreact/react-native-firestack#141]
Metadata is not propagated to native code.

https://github.com/fullstackreact/react-native-firestack/blob/master/android/src/main/java/io/fullstack/firestack/FirestackStorage.java#L157
Metadata map is destructured but never used.

**Comment by Salakar** [comment]
@Yarikx will sort on my branch (which is going to be merged for v3)

**Comment by Yarikx** [comment]
@Salakar Cool!

**Comment by Salakar** [comment]
Done, on my branch.

**Comment by auser** [comment]
Looking forward to merge this -- working on tests

**Comment by Salakar** [comment]
Closing as fixed on v3 branch.
