### ISSUE TITLE
libFirestack.a?

### ISSUE THREAD

**Issue by marclundgren** [fullstackreact/react-native-firestack#15]
Where can I find `libFirestack.a`?

I'm following step 1 in the [manual setup steps](https://github.com/fullstackreact/react-native-firestack#manually)

**Comment by auser** [comment]
Holla @marclundgren What do you mean? Did you call `react-native link react-native-firestack`?

**Comment by auser** [comment]
@marclundgren Okay, I've got it... I forgot to list a step on the installation process for manually linking. I'll update the readme shortly, but for you:

Make sure you add the `Firestack` library in the `Libraries` list
