### ISSUE TITLE
Custom Events are not getting registered on Android.

### ISSUE THREAD

**Issue by rohitgoyal** [fullstackreact/react-native-firestack#163]
Hi
I have successfully integrated Firestack in my react-native project. I am using it to implement Firebase analytics. 
The analytics is working perfectly fine in iOS. I am getting all session reports as well as all the custom events are visible in Firebase console.

In Android however I am not getting any custom event reports while the session reports are working in Android as well. 
Below is the code for sending custom events. 

```
firestack.analytics.logEventWithName("join_game", {
     'screen': 'Home'
    })
   .then(res => console.log('firebase: Sent event named join game'))
   .catch(err => console.error('firebase: You should never end up here'));
```

With this while running on iOS I am getting the log 'firebase: Sent event named join game' but there is no such log when I am running this on Android. 

Here is my google-services.json file setting for services

```
"services": {
        "analytics_service": {
          "status": 2
        },
        "appinvite_service": {
          "status": 1,
          "other_platform_oauth_client": []
        },
        "ads_service": {
          "status": 1
        }
      }
```

Any ideas?

**Comment by Ehesp** [comment]
Have you tried [this fork](https://github.com/Salakar/react-native-firestack), or the v3 branch?

cc @Salakar

**Comment by Salakar** [comment]
`firestack.analytics().logEvent()` on my fork/v3 branch - android was missing on master so probably why its not working for you @rohitgoyal

**Comment by rohitgoyal** [comment]
@Ehesp @Salakar 
Update: I am using the main repo of [firestack](https://github.com/fullstackreact/react-native-firestack).  Also now I see the events in Firebase console but I still don't get the success log for Android.

**Comment by Salakar** [comment]
@rohitgoyal there is no logevent implemented on the master branch, can you give v3 branch a go, I implemented it on there

**Comment by Salakar** [comment]
Fixed on upcoming v3, closing issue.
