### ISSUE TITLE
Add missing `invariant` package

### ISSUE THREAD

**Issue by NoelBroda** [fullstackreact/react-native-firestack#164]
Looks like `lib/firestackModule.js` file is using `invariant` module, but it's not in the `package.json` file.

I added `react-native-firestack` to my project and I'm getting this issue.

After run `npm install invariant --save` I could fixed it and continue working.

**Comment by Ehesp** [comment]
Good spot. I thought React Native installed this anyway which should have caught it. Could you make a PR on this side for it?

**Comment by NoelBroda** [comment]
Sure! I'll check it tonight

**Comment by NoelBroda** [comment]
I'm adding `"invariant": "^2.2.2"`, and checking another errors.

**Comment by NoelBroda** [comment]
@Ehesp which is the invariant version that you are using?
And which babel version? Looks like you had it installed globally. I want to add it as local package, in devDependency, so everybody can start working with no problems.

**Comment by NoelBroda** [comment]
Oh wait... I just realize you are not using a build. So, `npm run build` is odd?

**Comment by NoelBroda** [comment]
https://github.com/fullstackreact/react-native-firestack/pull/166

**Comment by moooji** [comment]
@NoelBroda This can be closed, or?
