### ISSUE TITLE
ref.push() should return an object instead of a promise

### ISSUE THREAD

**Issue by neverlan** [fullstackreact/react-native-firestack#169]
According to https://firebase.google.com/docs/database/web/read-and-write, the push method should return an object to get the item key without waiting to resolve the promise.

This is useful to work offline and have our UI responding instantly without waiting for the server response.

We could implement something like this:
const { key, promise } = ref.push(item);

**Comment by auser** [comment]
@Salakar @Ehesp ^^

I think you're right.

**Comment by Ehesp** [comment]
@auser it makes sense, risk vs reward haha

**Comment by florianbepunkt** [comment]
#171 

`push()` should  return an object only when it's called without data. asfaik this is how it's handled in js SDK. so `ref('/somePath').push({'my': 'object'})` returns a promise whereas `ref().push()` is a synchronous call and returns an object.

**Comment by Salakar** [comment]
@florianbepunkt ah ye correct, https://firebase.google.com/docs/reference/js/firebase.database.Reference#push - returns a thenable ref - should still be doable

**Comment by moooji** [comment]
This has been solved in v3 (https://github.com/fullstackreact/react-native-firestack/issues/231).
