### ISSUE TITLE
download file from storage

### ISSUE THREAD

**Issue by kendrickkesley** [fullstackreact/react-native-firestack#17]
Hi! I was wondering if this library can download file from firebase storage
I'll be using this on Android

Thanks!

**Comment by auser** [comment]
When you say download, do you mean and save on device or get the db url?

**Comment by kendrickkesley** [comment]
just get the db url,
thanks!

**Comment by auser** [comment]
Yes it does (working on Android implementation now). I'll add docs on it as well when I'm done.

**Comment by kendrickkesley** [comment]
Ah thanks you! :)

**Comment by auser** [comment]
No problem. And it's confirmed on both platforms. I'll add docs on it tonight.
