### ISSUE TITLE
[v3] Impossible to register multiple listeners to the same ref on iOS

### ISSUE THREAD

**Issue by jirotheone** [fullstackreact/react-native-firestack#170]
It is impossible to register multiple listeners to the same ref on iOS.
Example:

const LIST_KEY = 'path/to/data';
firestack.database.ref(LIST_KEY).on('value', handleValueChange);
firestack.database.ref(LIST_KEY).on('value', handleValueChange2);

The second listener never gets registered and instead throws a warning when the callback is called (possible promise reject).
On Android the same implementation works fine.

**Comment by Ehesp** [comment]
cc @chrisbianca : Did you fix this in v3?

**Comment by chrisbianca** [comment]
@Ehesp No, I don't think I've touched this in v3.

The question here is should the multiple listeners be handled on the JS side of the bridge or in the native code? @auser what are your thoughts?

My gut is that the JS side should handle it, as currently if you add two listeners to the same ref on the native side, I *think* you'll end up with essentially the same event getting sent twice.  As such, each of the listeners on the JS side will get fired twice.

To work around this, you'd need to uniquely identify each listener and attach this to the event which may be a bit of overkill.

**Comment by auser** [comment]
I think the `JS` side is more flexible and is a better place to handle this. We still need to keep track of the listeners on the native side, but it's probably easier to register them with a unique name on the native side generated and passed down from the JS. 

What do you think about that, @chrisbianca @Salakar @Ehesp ?

**Comment by jirotheone** [comment]
Just for the record, our workaround was to extend the "ref" and the "on" references to generate a unique ID to each listener on the JS side and manage the callbacks inside our application.
The problem was that every callback function had the same ID, so we included a generated hash on the prototype of the function, allowing the firestack to know which listener to detach on the "off" call. (:

**Comment by Salakar** [comment]
I believe @chrisbianca fixed this (your subscriptions changes)

@jirotheone could you give v3 branch a whirl please - just keep in mind its now matching the FB web sdk. (plus lots of new shineys).
