### ISSUE TITLE
V3: ref().push().set({}) does not mimic js sdk

### ISSUE THREAD

**Issue by florianbepunkt** [fullstackreact/react-native-firestack#171]
Hi @Salakar, I noticed an inconsistency with the js sdk…

What I'm trying to do is to use push but save the uid that push generates within the object. With firebase js sdk, you would do it like this

```
// Create a new post reference with an auto-generated id
var newPostRef = postListRef.push();
newPostRef.set({
    // ...data goes here
    // now you can use the generated uid with newPostRef.key
});
```

see here: https://firebase.google.com/docs/database/web/lists-of-data

with firestack v3 this doesn't work, since you promisify the push() result regardless whether there is a server interaction or not. If I'm correct, than in firebase JS sdk a .push operation with an empty object is a synchronous, client-side only operation.

**Comment by Ehesp** [comment]
@florianbepunkt Currently, push returns a promise since it has to interact with native code to get the new Firebase ID. On Salakars local branch, there is a work around in place to mimic web functionality however there was a bit of a debate on Gitter about it.

**Comment by Salakar** [comment]
@florianbepunkt @Ehesp - what Elliot said really, i've done quite a bit of work on getting this working as per js sdk on my local branch as well as getting SERVER_OFFSET working synchronously also, but it's not been pushed up yet as its a WIP - plus the whole debate about it.

**Comment by florianbepunkt** [comment]
@Salakar I really don't mind the promise way at all, so it's not really an issue for me, I just noticed it. But seems like you already tackled it.

> I don't see any chance of firebase changing the algorithm due to the fact this would break a lot of core firebase functionality for everyone on top of every sdk out there

I agreee, at least I don't see a change like this coming in firebase v3 version cycle.
