### ISSUE TITLE
V3: firestack.ServerValue.TIMESTAMP

### ISSUE THREAD

**Issue by florianbepunkt** [fullstackreact/react-native-firestack#173]
Is this implemented? I get undefined for firestack.ServerValue.TIMESTAMP using the current v3 branch from this repo.

Or has the syntax for this changed?

Thank you.

**Comment by florianbepunkt** [comment]
okay, if anyone else stumbles upon this… syntax is different from js SDK. firestack.ServerValue returns a promise.

```
return firestack
      .ServerValue
      .then((ServerValue) => {
          // you can use ServerValue.TIMESTAMP now
       })
```

**Comment by Salakar** [comment]
@florianbepunkt I have this working locally the same as the web api, synchronously - as per your first example. Internally uses the built in FB ref `.info/serverTimeOffset` to keep it up to date.

I need to push up my local sometime, just not sure it's in a safe state yet as i've done quite a lot on it.  Working on it though!

**Comment by florianbepunkt** [comment]
@Salakar Great. I'll try it when you push it.

**Comment by Salakar** [comment]
@florianbepunkt keeping open for v3 milestone

**Comment by Salakar** [comment]
@florianbepunkt 

Pushed this up, syntax is as follows now: 

```javascript
// very random example
const db = firestack.database();
const ref = db.ref('users/boatymcboatface');

ref.child('sessions').push(db.ServerValue.TIMESTAMP);
```

As you can see its now like the web sdk, no need to use a promise to get server val. Same with push.

Give it a whirl when you can :)

**Comment by alxvallejo** [comment]
RIght away i get firestack.database is not a function when i try to declare it.
