### ISSUE TITLE
IOS - FirestackAuth - No known class method for selector...

### ISSUE THREAD

**Issue by blumanski** [fullstackreact/react-native-firestack#176]
Xcode is failing to build

    .........../node_modules/react-native-firestack/ios/Firestack/FirestackAuth.m:490:45: 
    No known class method for selector 'credentialWithIDToken:accessToken:'

**Comment by auser** [comment]
Are you working off the master branch, v3, or npm?

**Comment by neverlan** [comment]
Same error. 2.3.4 from npm.

**Comment by blumanski** [comment]
@auser 
i work from master

cheers

**Comment by redwind** [comment]
got same error with npm

**Comment by Ehesp** [comment]
Try v3 branch guys.

**Comment by neverlan** [comment]
Xcode is still failing to build on v3:

/node_modules/react-native-firestack/ios/Firestack/FirestackCloudMessaging.m:74:28: Expected method body

**Comment by yn5** [comment]
Same here.

Firestack 2.3.4.

**Comment by yn5** [comment]
Fixed the npm dependency version at 2.3.3 which works for now.

**Comment by auser** [comment]
Fixes with latest push/update.
