### ISSUE TITLE
Android build failing - FirestackCloudMessaging.java:127: error:

### ISSUE THREAD

**Issue by blumanski** [fullstackreact/react-native-firestack#182]
The nmp and the master have that problem at the moment.    

    node_modules/react-native-firestack/android/src/main/java/io/fullstack/firestack/FirestackCloudMessaging.java:127: error: cannot access AbstractSafeParcelable
                RemoteMessage remoteMessage = intent.getParcelableExtra("data");

**Comment by blumanski** [comment]
Error is gone now...
I run 
    └── react-native-firestack@2.3.5 
    "react-native-firestack": "^2.3.5",

The versions are a bit confusing, npm install is installing version 2.3.4

**Comment by rigobcastro** [comment]
@blumanski Hi, I have the same error with the version 2.3.6. What was your solution? Thanks!

```
:react-native-firestack:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/Users/user/App/node_modules/react-native-firestack/android/src/main/java/io/fullstack/firestack/FirestackCloudMessaging.java:127: error: cannot access AbstractSafeParcelable
                RemoteMessage remoteMessage = intent.getParcelableExtra("data");
                                                    ^
  class file for com.google.android.gms.common.internal.safeparcel.AbstractSafeParcelable not found
/Users/user/App/node_modules/react-native-firestack/android/src/main/java/io/fullstack/firestack/FirestackMessagingService.java:29: error: no suitable method found for putExtra(String,RemoteMessage)
        i.putExtra("data", remoteMessage);
```

**Comment by JonghunYu** [comment]
@rigobcastro I resolved this issue by reverting this commit
https://github.com/fullstackreact/react-native-firestack/commit/7cb0a0891394d33ee2319981cb321efec6535980 since version of google play service and firebase should be same.
