### ISSUE TITLE
[V3] on('value') listener fires twice

### ISSUE THREAD

**Issue by florianbepunkt** [fullstackreact/react-native-firestack#184]
Not sure if this is a firebase issue, intended behaviour or an issue with firestack.

i have a reference that I attach a listener to.

```
var messagesRef = firestack
  .database()
  .ref('messages')
  .child(matchID)
  .orderByChild('createdAt')
  .startAt(moment().valueOf())
  .limitToLast(1);

messagesRef.on('value', function(snapshot) {
    console.log('snapshot', snapshot);
  });
});
```

the console.log fires twice where I would exspect it to fire only once. first I thought I added the listener twice, but I checked and it's not the case.

If I changed the listener to child_added, it fires only once as exspected

```
messagesRef.on('child_added', function(snapshot) {
    console.log('snapshot', snapshot);
  });
});
```

**Comment by Salakar** [comment]
@florianbepunkt have you got persistence enabled? 

If so: Firebase returns the locally persisted value immediately followed by the server value so firing twice is to be expected. Worth noting that using a .once on persistence will always return the local data, never from the server. (it gets updated after receiving a response, but will always be behind)

If you don't have it enabled then can you try the v3 branch again (its been pushed up again today) and see if you have the same issue.

**Comment by Salakar** [comment]
Might also be related to: https://github.com/fullstackreact/react-native-firestack/issues/170

**Comment by florianbepunkt** [comment]
@Salakar Yes, I have persistence enabled. Didn't know about this behaviour but totally makes sense. Thanks for the heads up. I'll try to give the new updates a go next week… stuck in another project atm.
