### ISSUE TITLE
[V3] Enhancement - support ref.parent with snapshot

### ISSUE THREAD

**Issue by florianbepunkt** [fullstackreact/react-native-firestack#185]
I noticed that you can't get the parent of a reference as in JS SDK: https://firebase.google.com/docs/reference/js/firebase.database.Reference#parent

in my specific case I need to get the parent path/key from a snapshot, which in JS SDK I would do liek this

```
function (snapshot) {
   snapshot.ref().parent().key;
}
```

EDIT: To clarify… when I have a normal database ref, getting the key of the parent works. but not with a snapshot.

**Comment by florianbepunkt** [comment]
digging through code I noticed that snapshot.ref returns a Database object and not a Reference Object.

**Comment by Ehesp** [comment]
https://github.com/Salakar/react-native-firestack/commit/57df0780d75497ac02720451247cd22ae1cfdda2

**Comment by Salakar** [comment]
@florianbepunkt this has been implemented on my fork as per web API it's a getter method, so usage is slightly diff from your example:

```javascript
function(snapshot) {
  const parentRef = snapshot.ref.parent;
  // ... do something else
}
```

https://github.com/Salakar/react-native-firestack/blob/master/lib/modules/database/reference.js#L292

Closing as now complete.

**Comment by Salakar** [comment]
@florianbepunkt actually my bad, thought this was fixed, it wasn't, just pushed a fix so it is now =]

**Comment by florianbepunkt** [comment]
@Salakar Great, thank you. Hope I can check it out soon.
