### ISSUE TITLE
[v3] – FirestackCloudMessaging.m: expected method body

### ISSUE THREAD

**Issue by stilva** [fullstackreact/react-native-firestack#188]
I get an error when I try to build an empty RN project using Firestack from the branch `v3`.

I get the following error:

```
/[...]/TestProject/node_modules/react-native-firestack/ios/Firestack/FirestackCloudMessaging.m:74:28: error: expected method body
- (void) requestPermissions(NSDictionary *)requestedPermissions
```

**Current environment**:
**OS X** 10.12.1
**XCode** 8.1 & 7.2.1
**react-native-cli**: 2.0.0
**react-native**: 0.39.1

**Steps to reproduce**:
`react-native init TestProject`
`cd TestProject`
The app compiles and runs properly at this stage.

`npm i -S fullstackreact/react-native-firestack#v3`
`react-native link react-native-firestack`
`cd ios && pod update --verbose`
`cd .. && react-native run-ios`

This is where I start getting the aforementioned error.
Same error when I try to run the project from `TestProject.xcworkspace`

Has anyone else encountered this issue?

**Comment by stilva** [comment]
For what it's worth, I'm not having the issue while using `v3` on #167

**Comment by Salakar** [comment]
@chrisbianca is this something you could possibly look at? :)

**Comment by chrisbianca** [comment]
@Salakar I've just tried this with the latest v3 and it compiles fine.

@stilva Can you confirm if this is still an issue?

**Comment by Salakar** [comment]
@chrisbianca @stilva sounds like an incorrectly setup project to me

Have made a note to review install docs sometime.

**Comment by stilva** [comment]
Can confirm this has been fixed. Thanks!
