### ISSUE TITLE
Bitcode is not enabled for real device iOS builds

### ISSUE THREAD

**Issue by IjzerenHein** [fullstackreact/react-native-firestack#19]
Hi,

First of all I'd like to thank you for creating this awesome library, kudos! 👍 👍 

When building for my actual phone on iOS I'm getting an error that bitcode is not enabled in `libFirestack.a`. I checked the firestack project and it is indeed disabled there. Is this on purpose and if so what dependency requires that bitcode is not enabled.
I'm currently stuck with my build on this as I really don't want to disable the bitcode option.

![image](https://cloud.githubusercontent.com/assets/6184593/18250885/38884716-7386-11e6-98fb-c6de35ddbb9e.png)

best regards,
Hein

**Comment by auser** [comment]
Hein,

Thanks for the note. You're the second to ask for this (thanks for making the issue). I disabled it previously as bit-code caused a build error previously. I don't recall the specific reason why I had it disabled, but I will investigate and report back.

**Comment by IjzerenHein** [comment]
Awesome! If I can be of any assistance let know.
Cheers, Hein

**Comment by IjzerenHein** [comment]
Btw, quick other question. I've integrated Firebase Crash reporting in my App. Complete with console.log interception and correct callstacks (both iOS and Android). Would you be interested in having this code to the firestack codebase?

**Comment by auser** [comment]
Hein,
Absolutely! I've been meaning to put that on the feature list!

**Comment by IjzerenHein** [comment]
Alright cool. It's really busy at the moment, but I'll to create a pull request for it anytime soon.

**Comment by auser** [comment]
Hein,

Let me know if you want some help on how to integrate it.

**Comment by IjzerenHein** [comment]
Yeah, well most of it is pretty straightforward to integrate. The only tricky thing is that when building the bundle, it also needs to generate sourcemaps. I've modified my scripts for it, but not sure how that would need to be done automatically when installing the firestack lib (or using `react-native link`). I'll have a closer look when I have more time.

**Comment by IjzerenHein** [comment]
And yeah, having it in a separate module such as `crash` would definitely also make sense to me. 👍

**Comment by IjzerenHein** [comment]
Btw, I was using the storage API's today and noticed the examples in the README are out of date.
It says 'firestack.uploadFile` but it should be `firestack.storage.uploadFile`. But you're probably already aware of this :)

**Comment by auser** [comment]
Oh yes! Can you make a PR with that update?

**Comment by auser** [comment]
Okay, I recall why bit-code needed to be disabled. Firestack is built as a dynamic library, which needs to be linked against static libraries (React). Until we find a way to dynamically link Firestack to React, we can't enable bitcode.

Any suggestions?

**Comment by auser** [comment]
As of now, I can't enable bitcode due:

1. bitcode and the undefined flag are opposites (for obvious reasons, but we cannot build a library that cannot find it's symbols, but cannot build a dynamic library without using `-undefined` flag (yet).
2. Setting the build to a static library does not allow our app to find the Firebase libraries
3. Setting the build to a dynamic library does not allow our app to use bitcode

I'm going to mark this as wontfix for now, until we can figure out a different build mechanism.

**Comment by auser** [comment]
I *think* I fixed the `bitcode` issue. I pushed the latest update to the `feature/bitcode` branch, if you're interested in trying it out in your app.
