### ISSUE TITLE
Is there a way to register event with value?

### ISSUE THREAD

**Issue by rohitgoyal** [fullstackreact/react-native-firestack#190]
Hi 
This library works perfectly fine. I am using it for the Firebase Analytics. Is there any way I can send the eventName with value?

Thanks!

**Comment by Salakar** [comment]
@rohitgoyal check out the v3 branch and the firebase analytics sdk [here](https://github.com/Salakar/react-native-firestack/blob/master/lib/modules/analytics.js)

**Example:**

```javascript
firestack.analytics().logEvent('foobar', {
    foo: 'bar',
});
```
