### ISSUE TITLE
Firebase Analytics

### ISSUE THREAD

**Issue by theobouwman** [fullstackreact/react-native-firestack#192]
When I log an event with a nam using the code below it is not clear to me where I can see the data that is passed as second parameter in Firebase.
```
firestack.analytics.logEventWithName("starred", {
       'receiver': uid,
       'star': like
})
```

**Comment by Salakar** [comment]
I believe you need to link your fb project with google analytics to view in depth data, the firebase console is limited in what it displays analytics wise.

Also, might be worth using the v3 branch, analytics has been updated a lot, missing methods added and now has ios plus android support. New analytics api [here](https://github.com/Salakar/react-native-firestack/blob/master/lib/modules/analytics.js) - let me know if you have any issues with it.

Closing as not a firestack issue, you should check out the official firebase slack community - lots of helpful people there :)
