### ISSUE TITLE
Exception '*** setObjectForKey: key cannot be nil' was thrown while invoking uploadFile on target FirestackStorage

### ISSUE THREAD

**Issue by coffeeandjunk** [fullstackreact/react-native-firestack#195]
![img_3242](https://cloud.githubusercontent.com/assets/3206580/21440746/89c60bf2-c8ba-11e6-9567-27282d79c4cf.jpg)

Getting this error when trying to upload a small video (~839KB). I wonder if I've made some silly mistake in the code somewhere.

Here's the react-native-camera snippet.

```
startRecording() {
    if (this._camera) {
      this._camera.capture({
        mode: constants.CaptureMode.video,
      })
        .then((data) => {
          const firestack = new Firestack();
          const filename = 'somevideo.mov';
          firestack.storage.setStorageUrl('ftw-group-messaging-app.appspot.com');
          firestack.storage.uploadFile(`videos/${filename}`, data.path, {
            contentType: 'video/mov',
          })
          .then((res) => {
          console.log('result from upload file: ', res);
          })
          .catch((err) => {
            console.log('error happened with uploadFile', err);
          });
        })
        .catch(err => console.error(err));
      this.setState({
        isRecording: true,
      });
      setInterval(this.stopRecording, 3500);
    }
  }
```

**The error goes away after reloading once. But nothing happens. No file gets uploaded.**

**Comment by iamkyleee** [comment]
Hi I have the same error. have you solved it? @coffeeandjunk

**Comment by vadi7mir** [comment]
Same issue here... The only difference in my case is contentType = "image/jpeg";

**Comment by vadi7mir** [comment]
@auser Please help me with this issue. Spent so much time on time and feel desperate now... What I noticed recently is this:
1) When I run react-native run-ios, go to profile, and then immediately change profile picture everything ends with this crash (like on the picture above);
2) If after start I press Cmd+R to refresh app in the simulator and do the same the picture gets updated successfully.
I have no a faintest idea of the reason.

Thank you in advance!

**Comment by coffeeandjunk** [comment]
I was unable to solve it. I didn't face this issue with images though. And no, I didn't use react-native-image-picker. I moved out of firestack (temporarily) as I couldn't find a way to solve it. I'll review this error sometime in next month. If it still persists, I'll see if I can solve it somehow.

**Comment by iamkyleee** [comment]
I was able to solve my problem by importing the json from Firebase to the project by dragging it via xcode not finder

Do the other firebase service work like database?

**Comment by auser** [comment]
Ah just seeing this. Yes, you have to do it via Xcode, otherwise the compiler doesn't know it needs to be linked. 
Thanks for the comment @iamkyleee. For the same reason, all services in Xcode work like this.

**Comment by vadi7mir** [comment]
@auser don't know why you decided to close this. @iamkyleee I've done it of course. If I hadn't done it, this wouldn't trigger crash just sometimes. Above I described that most often it only appears before I reload the app. =(
