### ISSUE TITLE
Keychain Issue

### ISSUE THREAD

**Issue by walkerdigital** [fullstackreact/react-native-firestack#206]
When I initially added firestack into my RN app it worked great.  All of a sudden I started getting an error when attempting to use the Authentication.

The err being thrown is:

```json
17995
description
:
"Unknown error"
name
:
"signinError"
rawDescription
:
"An error occurred when accessing the keychain. The @c NSLocalizedFailureReasonErrorKey field in the @c NSError.userInfo dictionary will contain more information about the error encountered"
userInfo
:
"{↵    NSLocalizedDescription = "An error occurred when accessing the keychain. The @c NSLocalizedFailureReasonErrorKey field in the @c NSError.userInfo dictionary will contain more information about the error encountered";↵    NSLocalizedFailureReason = "SecItemAdd (-34018)";↵    "error_name" = "ERROR_KEYCHAIN_ERROR";↵}"
__proto__
:

```

For 2 days I've been digging and tried about a dozen things to get XCode to fix the problem.  When I run in Simulator from XCode (by clicking the play button) it seems to work fine.  When I use the react-native-cli to run-ios is when I see the issue.

* XCode 8.2.1
* OSX Sierra 10.12.2

My dependancies:

```json
  "dependencies": {
    "apisauce": "^0.6.0",
    "firebase": "^3.6.1",
    "format-json": "^1.0.3",
    "lodash": "^4.17.2",
    "querystringify": "0.0.4",
    "ramda": "^0.22.1",
    "react": "15.3.1",
    "react-native": "^0.37.0",
    "react-native-animatable": "^0.6.0",
    "react-native-config": "^0.1.2",
    "react-native-device-info": "^0.9.6",
    "react-native-drawer": "^2.3.0",
    "react-native-firestack": "^2.3.5",
    "react-native-i18n": "^0.1.1",
    "react-native-maps": "^0.11.0",
    "react-native-router-flux": "^3.37.0",
    "react-native-vector-icons": "^3.0.0",
    "react-redux": "^4.4.6",
    "redux": "^3.6.0",
    "redux-logger": "^2.7.4",
    "redux-persist": "^3.5.0",
    "redux-saga": "^0.13.0",
    "reduxsauce": "0.2.0",
    "seamless-immutable": "^6.3.0"
  },
  "devDependencies": {
    "ava": "^0.17.0",
    "babel-eslint": "^7.1.1",
    "babel-preset-es2015": "^6.18.0",
    "enzyme": "^2.6.0",
    "flow-bin": "0.33.0",
    "ghooks": "^1.3.2",
    "mockery": "^2.0.0",
    "nyc": "^9.0.1",
    "react-addons-test-utils": "^15.3.1",
    "react-dom": "^15.4.0",
    "react-native-mock": "^0.2.8",
    "reactotron-apisauce": "^1.5.2",
    "reactotron-react-native": "^1.5.2",
    "reactotron-redux": "^1.5.2",
    "reactotron-redux-saga": "^1.5.2",
    "snazzy": "^5.0.0",
    "standard-flow": "^1.0.0"
  }
  
```

Finally...The code generating this error

```js
import { put } from 'redux-saga/effects'
import LoginActions from '../Redux/LoginRedux'
import { Actions as NavigationActions } from 'react-native-router-flux'
import Firestack from 'react-native-firestack'

const firestack = new Firestack();

export function * login ({ username, password }) {

	
	// return { 'status': 'failure', 'error': "Disaster" }
	// yield put(LoginActions.loginFailure("Disaster"))

	try {
		const userDat = yield firestack.auth.signInWithEmail(username, password)
		  .then((user) => {
		    return { 'status': 'success', 'user': user }
		  })
		  .catch((err) => {
		  	console.log(err);
		  	 return { 'status': 'failure', 'message': err.description }
		  });

		if(userDat.status == 'success') {
			yield put(LoginActions.loginSuccess(userDat.user.user))
		} else {
			yield put(LoginActions.loginFailure(userDat.message))
		}
		
	} catch(e) {
		yield put(LoginActions.loginFailure('Problem'))
	} 

}
```

The only consistent "solution" I've found when searching online is to enable "Keychain Sharing" in XCode - which I've done.  

![lc xcodeproj 2017-01-03 14-36-29](https://cloud.githubusercontent.com/assets/21980428/21622258/418e04aa-d1c2-11e6-8d89-af007a9fe906.jpg)

I would really appreciate any insight anyone might be able to offer.

**Comment by Salakar** [comment]
@walkerdigital 

Firebase Authentication state is shared between different apps when running on the iOS Simulator. 

When running two or more applications that use Firebase Authentication on the same iOS simulator, there is a issue with the iOS keychain that causes the authentication state to be shared across the different applications. 

This means that if you sign in to an app, and later open a second app, you may find a user to be signed in into it. 

**Workaround:** either don't use two different applications with Authentication on the same simulator instance, or manually sign out from the applications between tests.

Try the 'workaround' and let me know if this sorts your issue.

**Comment by walkerdigital** [comment]
Thanks for the suggestion.  Ultimately what I did was generate a new app and drag over all of my ./App contents and it started working as expected.  I had done this before I read your suggest but if I encounter again I will certainly give this a try.  Unfortunately I deleted the version of the project which wasn't working.

I appreciate the help!
