### ISSUE TITLE
app crashing on launch. "java.lang.NoSuchMethodError: No static method "

### ISSUE THREAD

**Issue by texas697** [fullstackreact/react-native-firestack#207]
The app builds and installs on the phone. however it crashes immediately. I have found this via adb logcat

java.lang.NoSuchMethodError: No static method zzb(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; in class Lcom/google/android/gms/common/internal/zzaa; or its super classes (declaration of 'com.google.android.gms.common.internal.zzaa' appears in /data/app/com.m

com.google.firebase.provider.FirebaseInitProvider.zza(Unknown Source)com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source)

**Comment by morelazers** [comment]
hey @texas697 - how did you solve this?

**Comment by morelazers** [comment]
Did you find a solution @texas697? If I install `react-native-onesignal` I get this error, but I'm not sure which repo is the culprit.

**Comment by texas697** [comment]
yes I did, sorry for the delayed response
I made 2 scripts in my package.json to to make changes

 "fix-map-module": "ex -sc '%s/9.8.0/+/g|x' node_modules/react-native-maps/android/build.gradle",
    "fix-firestack-module": "ex -sc '%s/9.8.0/+/g|x' node_modules/react-native-firestack/android/build.gradle",

**Comment by morelazers** [comment]
Nice, thanks!

**Comment by ScholtenSeb** [comment]
Hi @texas697 

What did you do after adding the extra scripts to package.json?
