### ISSUE TITLE
Best way to initialize and use firestack

### ISSUE THREAD

**Issue by IjzerenHein** [fullstackreact/react-native-firestack#21]
Hi, I've got a question concerning how to use the library.
According to the config I have to create an firestack instance like this:

```js
const firestack = new Firestack();
```

However, what if I'm using Firestack in multiple files? Can I create a new instance per file in which I need it? Is this the preferred approach?

```javascript
// file1.js
import Firestack from 'react-native-firestack';
const firestack = new Firestack();

... do some logic here
```

```javascript
// file2.js
import Firestack from 'react-native-firestack';
const firestack = new Firestack();

... do some logic here
```

Cheers, Hein

**Comment by auser** [comment]
Hein,

Thanks for the question. It's actually a singleton object, so you can call `new Firestack()` and it will reference the same object.
