### ISSUE TITLE
Use of undeclared identifier 'RCTReloadNotification'

### ISSUE THREAD

**Issue by jvorcak** [fullstackreact/react-native-firestack#218]
Hi guys,

I've created a fresh react native project today using RN 0.40.0.
I've added RNF using `yarn add react-native-firestack` && `react-native link` && `cd ios && pod update --verbose`

I've opened `ios/[YOUR APP NAME].xcworkspace` file and I'm getting the following error when building the project

```/Users/.../node_modules/react-native-firestack/ios/Firestack/Firestack.m:58:59: Use of undeclared identifier 'RCTReloadNotification'```

This is not my first time building RNF and I never experienced this, is it possible that it's a possible regression? It's easily reproducible for every new RN project.

Thank you for your help

**Comment by auser** [comment]
Are you using Messaging?

**Comment by jvorcak** [comment]
I think so ...
```
Downloading dependencies
Using Firebase (3.11.0)
Using FirebaseAnalytics (3.6.0)
Using FirebaseAuth (3.1.0)
Using FirebaseCore (3.4.6)
Using FirebaseDatabase (3.1.1)
Using FirebaseInstanceID (1.0.8)
Using FirebaseMessaging (1.2.1)
Using FirebaseRemoteConfig (1.3.1)
Using FirebaseStorage (1.0.5)
Using GTMSessionFetcher (1.1.7)
Using GoogleInterchangeUtilities (1.2.2)
Using GoogleSymbolUtilities (1.1.2)
Using GoogleToolboxForMac (2.1.0)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 7 dependencies from the Podfile and 13 total pods installed.
```

**Comment by IljaDaderko** [comment]
Upgraded react native re-linked all the pods and am getting this issue as well, I am not using Messaging at the moment.

**Comment by dcgoss** [comment]
It has been deprecated. See https://github.com/facebook/react-native/commit/286a1b2e5ef96328a585e9760a971ac034a6e56f, https://github.com/facebook/react-native/releases/tag/v0.40.0.
Trying to figure out how to replace it.

**Comment by slycoder** [comment]
I think the module should just respond to the invalidate selector?

**Comment by slycoder** [comment]
Actually, never mind, I'm not sure this code even needs to exist.  Reloads call dealloc then init so that should be enough.

**Comment by jvorcak** [comment]
Thanks for fixing, any chance this can be released and pushed to npm with a bumped version? I can of course link to master, but I think it can be highly confusing for people trying to link this library with react-native for new projects. @auser

**Comment by auser** [comment]
Done. Can you test it so I can close this?

**Comment by prontiol** [comment]
We also need this fix in v3.

**Comment by jvorcak** [comment]
I only got time to do this on Friday, I confirm it works. Thanks a lot for fixing this. 🎉  👍
