### ISSUE TITLE
[v3] Snapshot forEach does not behave like Web SDK

### ISSUE THREAD

**Issue by moooji** [fullstackreact/react-native-firestack#222]
The Web SDK Snapshot behaves like this:
```
ref.once('value', function(snapshot) {
  snapshot.forEach(function(childSnapshot) {
    var childKey = childSnapshot.key;
    var childData = childSnapshot.val();
    // ...
  });
});
```

Firestack v3 behaves differently:
```
ref.once('value', function(snapshot) {
  snapshot.forEach(function(childSnapshot) {
    var childData = childSnapshot;
  });
});
```

In my case, the problem is mostly that I do not get the child's `key` in the forEach loop.

**Comment by moooji** [comment]
I have submitted a PR that fixes this issue https://github.com/fullstackreact/react-native-firestack/pull/237

**Comment by Salakar** [comment]
Thanks for the PR 👍
