### ISSUE TITLE
RCTReloadNotification Removed.

### ISSUE THREAD

**Issue by TomAtterton** [fullstackreact/react-native-firestack#225]
RCTReloadNotification  has been removed from the newest version of react-native released 5 days ago (https://github.com/facebook/react-native/releases/tag/v0.40.0), yet still used in firestack.m 

<img width="771" alt="screen shot 2017-01-09 at 20 49 47" src="https://cloud.githubusercontent.com/assets/5540723/21780981/d739e254-d6ad-11e6-93d0-37b66e456714.png">

**Comment by AshokICreate** [comment]
I am getting this error when i run `project.xcworkspace.`

I am having same issue `use of undeclared identifier RCTReloadNotification`.

**Comment by TomAtterton** [comment]
Noticed this is a duplicate of #218
