### ISSUE TITLE
[v3] not issuing ID token.

### ISSUE THREAD

**Issue by esdrasportillo** [fullstackreact/react-native-firestack#230]
Hi, 

I am using the v3 branch and notice one thing: 

My app uses some backend service and in order to authenticate the user I use this [approach](https://firebase.google.com/docs/auth/admin/verify-id-tokens)

Using the master branch and calling the function `firestack.auth.getToken()` returns me some user information including the ID Token. But using the v3 branch using either `firestack.auth().currentUser.getToken()` or `firestack.auth().getToken()` does not return the id token but the refresh token which is not the token that is necessary to authenticate.

Printing the value of `firestack.auth().currentUser` I can see (in the middle of a huge json object) that the id token is there in some level of the object.

**Comment by esdrasportillo** [comment]
Quick fix is: `firestack.auth().currentUser._user.idToken`

**Comment by moooji** [comment]
@esdrasportillo Do you experience the issue on Android or iOS, or both?

**Comment by esdrasportillo** [comment]
I tested in iOS only, and unfortunately I can't test on Android since there are some other stuff in my app to fix that wouldn't allow me to launch the app right now.

**Comment by moooji** [comment]
Ok, I have the same problem on iOS, too. Unfortunately I cannot test Android either. I think `firestack.auth.getToken()` should not even exist if we try to mirror the Web SDK, because `getToken` is supposed to be a method on the user object. The 'official' way is to call `user.getToken()` or `firestack.auth().currentUser.getToken()` for example. This method does not seem to exist on user in v3 though for some reason, although it seems to be implemented here: https://github.com/fullstackreact/react-native-firestack/blob/v3/lib/modules/user.js#L96

**Comment by moooji** [comment]
I have submitted a PR https://github.com/fullstackreact/react-native-firestack/pull/233 that fixes this issue with `firestack.auth().getToken()`. There was a typo in the native iOS code which returns the user instead of the JWT token in `getToken`.

**Comment by esdrasportillo** [comment]
I can `firestack.auth().getToken()` does not work on v3 which is right.
But `firestack.auth().currentUser.getToken()` works for me in v3, the problem is that does not return the idToken.

**Comment by moooji** [comment]
Hmm, that's weird. For me it is exactly the other way around. The method `firestack.auth().currentUser.getToken()` does not seem to exist.

**Comment by Salakar** [comment]
@moooji @esdrasportillo getToken exist as per web SDK on v3 branch, e.g.

```javascript
if (firestack.auth().currentUser) {
    firestack.auth().currentUser.getToken().then((token) => {
        console.warn(token);
    })
}
```

@moooji that line you linked, the function on currentUser class just internally calls the auth classes getToken function, getToken though could probably just be moved directly into the user class and removed from auth() tbh.

**Comment by esdrasportillo** [comment]
It is working! Thanks!
