### ISSUE TITLE
[v3] Database .push() crashes on empty

### ISSUE THREAD

**Issue by petergerdes** [fullstackreact/react-native-firestack#231]
I'm trying to execute something like this:

firebaseApp.database().ref('kitchenSignUp').push().then((res) => {
        let newPostKey = res.key

        firebaseApp.ServerValue.then(map => {
          //Do update  
       })    
})

But push without a string or object gives: push is not a function. This worked in v2. If I pass an empty string it works, but then I get an empty string in firebase database as well. Not something I want :)

**Comment by moooji** [comment]
The issue seems to be that `push()` does not return a promise when used without arguments, but `push(something)` does.

This works:
```
const ref = firebaseApp.database().ref('kitchenSignUp').push();
console.log(ref.key);
```

To be consistent, I think it should always return a promise.

**Comment by moooji** [comment]
I have submitted a PR that fixes this issue and always returns from push with callback / promise https://github.com/fullstackreact/react-native-firestack/pull/234

**Comment by moooji** [comment]
According to @Salakar here https://github.com/fullstackreact/react-native-firestack/pull/234 and the Web SDK it seems that `push` is actually supposed to ONLY return with callback when a value has been supplied as argument. https://firebase.google.com/docs/reference/js/firebase.database.Reference#push

I have closed the PR and I guess this issue can be closed, too or @petergerdes?

The solutions:
```
const ref = firebaseApp.database().ref('kitchenSignUp').push();
console.log(ref.key);
```

**Comment by Salakar** [comment]
@petergerdes @moooji  you also don't need a promise for servervalue in v3, `firebase.database.ServerValue.TIMESTAMP` will just work

**Comment by petergerdes** [comment]
@Salakar That's great! Thanks!
