### ISSUE TITLE
[v3] [ios] React Native 0.40+ not supported

### ISSUE THREAD

**Issue by moooji** [fullstackreact/react-native-firestack#239]
React Native 0.40 has a major breaking change, which requires native code to be changed.

Before:
`#import "RCTUtils.h"`

But now all headers have been moved:
`#import <React/RCTUtils.h>`

https://github.com/facebook/react-native/releases/tag/v0.40.0

This is kinda straight forward to update, but will then unfortunately break compatibility with React Native before 0.40.

What do you think, shall v3 be the release for React Native 0.40+ and v2 the release for <= 0.39? Or maybe there should be already a v4 for 0.40+?

**Comment by moooji** [comment]
I have submitted a PR https://github.com/fullstackreact/react-native-firestack/pull/240

**Comment by Salakar** [comment]
Thanks for the pr =] merged
