### ISSUE TITLE
[v3] RCTReloadNotification error

### ISSUE THREAD

**Issue by IljaDaderko** [fullstackreact/react-native-firestack#243]
I was able to install v3 version firestack using `yarn add react-native-firestack@3.0.0-rc1` which could be an issue in the first place.

Never the less I am getting RCTReloadNotification error, that I believe was resolved on master, will this fix be added to v3 any time soon?

**Comment by moooji** [comment]
`RCTReloadNotification` has been removed from RN 0.40 and newer, I guess that might be the issue.

**Comment by IljaDaderko** [comment]
@moooji indeed, there are few similar issues floating arround #219 and #218, with #225 actually fixing the issue, but fix hasn't been applied to v3 branch yet.

**Comment by moooji** [comment]
This is "fixed" in the latest version of v3, but probably not in the npm package yet. This PR https://github.com/fullstackreact/react-native-firestack/pull/240 got merged today and removed the reference to `RCTReloadNotification`. You should not get the error anymore when using the latest v3 from this repo (not the npm version).

**Comment by auser** [comment]
Great, I'll push the next version of the `next` branch to `npm`.
