### ISSUE TITLE
Android compile error

### ISSUE THREAD

**Issue by funkysoul** [fullstackreact/react-native-firestack#244]
Since updating to RN 0.40 I'm getting this error when compiling for Android (iOS) works as expected, did anyone experience the same problem?

`:react-native-firestack:compileReleaseJavaWithJavac
/Users/admin/Documents/_Apps/react/DiveThru/node_modules/react-native-firestack/android/src/main/java/io/fullstack/firestack/FirestackCloudMessaging.java:127: error: cannot access AbstractSafeParcelable
                RemoteMessage remoteMessage = intent.getParcelableExtra("data");
                                                    ^
  class file for com.google.android.gms.common.internal.safeparcel.AbstractSafeParcelable not found
/Users/admin/Documents/_Apps/react/DiveThru/node_modules/react-native-firestack/android/src/main/java/io/fullstack/firestack/FirestackMessagingService.java:29: error: no suitable method found for putExtra(String,RemoteMessage)
        i.putExtra("data", remoteMessage);
         ^
    method Intent.putExtra(String,boolean) is not applicable
      (argument mismatch; RemoteMessage cannot be converted to boolean)
    method Intent.putExtra(String,byte) is not applicable
      (argument mismatch; RemoteMessage cannot be converted to byte)
    method Intent.putExtra(String,char) is not applicable
      (argument mismatch; RemoteMessage cannot be converted to char)
    method Intent.putExtra(String,short) is not applicable
      (argument mismatch; RemoteMessage cannot be converted to short)
    method Intent.putExtra(String,int) is not applicable
      (argument mismatch; RemoteMessage cannot be converted to int)
    method Intent.putExtra(String,long) is not applicable
      (argument mismatch; RemoteMessage cannot be converted to long)
    method Intent.putExtra(String,float) is not applicable
      (argument mismatch; RemoteMessage cannot be converted to float)
    method Intent.putExtra(String,double) is not applicable
      (argument mismatch; RemoteMessage cannot be converted to double)
    method Intent.putExtra(String,String) is not applicable
      (argument mismatch; RemoteMessage cannot be converted to String)
    method Intent.putExtra(String,CharSequence) is not applicable
      (argument mismatch; RemoteMessage cannot be converted to CharSequence)
    method Intent.putExtra(String,Parcelable) is not applicable
      (argument mismatch; RemoteMessage cannot be converted to Parcelable)
    method Intent.putExtra(String,Parcelable[]) is not applicable
      (argument mismatch; RemoteMessage cannot be converted to Parcelable[])
    method Intent.putExtra(String,Serializable) is not applicable
      (argument mismatch; RemoteMessage cannot be converted to Serializable)
    method Intent.putExtra(String,boolean[]) is not applicable
      (argument mismatch; RemoteMessage cannot be converted to boolean[])
    method Intent.putExtra(String,byte[]) is not applicable
      (argument mismatch; RemoteMessage cannot be converted to byte[])
    method Intent.putExtra(String,short[]) is not applicable
      (argument mismatch; RemoteMessage cannot be converted to short[])
    method Intent.putExtra(String,char[]) is not applicable
      (argument mismatch; RemoteMessage cannot be converted to char[])
    method Intent.putExtra(String,int[]) is not applicable
      (argument mismatch; RemoteMessage cannot be converted to int[])
    method Intent.putExtra(String,long[]) is not applicable
      (argument mismatch; RemoteMessage cannot be converted to long[])
    method Intent.putExtra(String,float[]) is not applicable
      (argument mismatch; RemoteMessage cannot be converted to float[])
    method Intent.putExtra(String,double[]) is not applicable
      (argument mismatch; RemoteMessage cannot be converted to double[])
    method Intent.putExtra(String,String[]) is not applicable
      (argument mismatch; RemoteMessage cannot be converted to String[])
    method Intent.putExtra(String,CharSequence[]) is not applicable
      (argument mismatch; RemoteMessage cannot be converted to CharSequence[])
    method Intent.putExtra(String,Bundle) is not applicable
      (argument mismatch; RemoteMessage cannot be converted to Bundle)
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors
:react-native-firestack:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.`

**Comment by jfmyers** [comment]
I've run into the exact same issue, although I'm running RN 0.38.

**Comment by jfmyers** [comment]
I downgraded to 2.3.6 and was still getting this issue. Once I downgraded `react-native-firestack` to 2.3.5 it started working. 

What changed, post version 2.3.5 that would be causing this issue on Android?

**Comment by auser** [comment]
I believe that's a firebase update, actually. Try downgrading your firebase dependencies. Does that fix it (for now)?

**Comment by designorant** [comment]
I've just ran into this with both 2.3.8 on RN 0.40. This is likely related to #182. However the app builds on 3.0.0-rc.2 (AKA @next).

Side note: I've seen some recently closed issues and merged PRs but it's a bit hard to figure out the differences between master/v3 and what's on NPM due to a [lack of tags](https://github.com/fullstackreact/react-native-firestack/tags). It would be amazing if we could keep these two in sync. I see @next on NPM but no clue how far is it behind master.

**Comment by funkysoul** [comment]
@jfmyers indeed rolling back to 2.3.5 on RN .40 works as expected. haven't touched the firebase dependencies though.

**Comment by auser** [comment]
@funkysoul I just pushed a new update. Can you try the latest version? I *think* I fixed it.

**Comment by funkysoul** [comment]
@auser Hi Ari, thanks for the rapid update, with the latest github/master version the compilation runs through but the app immediately quits after launch without any information..

**Comment by auser** [comment]
Can you drop me the adb logs?

**Comment by auser** [comment]
@funkysoul I'm going to be out until Monday. If you're not familiar with `adb`, you can get them using this command:

`adb logcat | grep $(adb shell ps | grep -i com.firestackapp | cut -c10-15)`

(obviously changing the `com.firestackapp` to the name of your application)

**Comment by funkysoul** [comment]
@auser thanks for your reply, I know how to use logcat but didn't knew about the cut command :-) thx for that.

Meanwhile I've figured that the immediate crash was being caused by react-native-maps.. but... the interesting thing is that it only crashes in combination with the latest npm & github version of firestack.  Rolling back firestack to 2.3.5 behaves normally as mentioned before.

After applying this fix: [react-native-maps #issue951 ](https://github.com/airbnb/react-native-maps/issues/951#issuecomment-272040280) everything works as expected no matter which version of firestack is used.

So with firestack 2.3.9 the android error is definitely gone. but I still wonder why rolling back firestack to 2.3.5 influences react-native-maps

**Comment by anantha322** [comment]
`:react-native-firestack:compileReleaseJavaWithJavac
/Users/admin/Documents/_Apps/react/DiveThru/node_modules/react-native-firestack/android/src/main/java/io/fullstack/firestack/FirestackCloudMessaging.java:127: error: cannot access AbstractSafeParcelable
RemoteMessage remoteMessage = intent.getParcelableExtra("data");
^
class file for com.google.android.gms.common.internal.safeparcel.AbstractSafeParcelable not found
/Users/admin/Documents/_Apps/react/DiveThru/node_modules/react-native-firestack/android/src/main/java/io/fullstack/firestack/FirestackMessagingService.java:29: error: no suitable method found for putExtra(String,RemoteMessage)
i.putExtra("data", remoteMessage);

I am getting same issue in android. Any body can help me out to resolve this bug

**Comment by funkysoul** [comment]
@anantha322 are you using the latest github version?

**Comment by anantha322** [comment]
@funkysoul : thanks, I updated ..it start working

**Comment by funkysoul** [comment]
@auser I think we can close this issue, as it's not really related to the module on its own. (though still wondering why this happens) ;-)
