### ISSUE TITLE
[v3] Firebase Setup docs: some inconsistencies in iOS instruction

### ISSUE THREAD

**Issue by IljaDaderko** [fullstackreact/react-native-firestack#246]
Docs referred to in this issue: https://github.com/fullstackreact/react-native-firestack/blob/v3/docs/firebase-setup.md

> Download the Firebase config file and place it in your app directory next to your app source code:

Image after this line shows that GoogleService-Info.plist should be placed within project file, where as following image from firebase shows it being placed within folder:

![Imgur](http://i.imgur.com/eJaywV4.png)

---

Is this an issue or should it be done as in docs?

**Comment by auser** [comment]
No, follow the firebase instructions. You need to include it in xcode.
