### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by iiitmanikanta** [fullstackreact/react-native-firestack#251]
**_Cannot read property 'MAIN_BUNDLE_PATH' of undefined_** red screen while importing Firestack using **import Firestack from 'react-native-firestack'**

**Comment by brianjd** [comment]
@iiitmanikanta It sounds like you didn't integrate the native portion properly.  Review your installation, and make sure you follow each of the steps [here](https://github.com/fullstackreact/react-native-firestack#installing).

**Comment by minhmera** [comment]
hi @iiitmanikanta i got the same issue on Android undefined " is not an object (evaluating 'FirestackStorage.MAIN_BUNDLE_PATH') " did u resolve your issue ? 
Thanks
