### ISSUE TITLE
[discussion] database.ref().push(); get key of generated child

### ISSUE THREAD

**Issue by mikesurowiec** [fullstackreact/react-native-firestack#26]
Hey there!

I was wondering if there's a better way to get the key of the child generated from a push()...
```js
firestack.database.ref('some-path').push({someItem: 'data'}).then((res) => {
  let childKey = _.last(res.name[0].split('/'));
});
```
Not sure if I'm missing something or if the function should change to include the generated key on the response. Also curious if `res.name[0]` will always be the correct path

Thanks!

**Comment by auser** [comment]
Hey @mikesurowiec 

Hey, thanks for asking! I just added a `key` getter to the DatabaseRef base class, so you can call it something slightly different:

```javascript
firestack.database.ref('some-path').push({someItem: 'data'}).then((res) => {
  let childKey = res.key;
});
```

**Comment by mikesurowiec** [comment]
You are awesome, thank you!
