### ISSUE TITLE
Better way to initialize

### ISSUE THREAD

**Issue by neosekar** [fullstackreact/react-native-firestack#262]
Can please tell me the best way to initialize the firestack in router-flux navigation?. I need to access the firestack in different reducers. Currently i am using react native starter app https://github.com/mcnamee/react-native-starter-app. I am new to react native so, can you please help me in this?

**Comment by auser** [comment]
Sure. You can import the instance from another file. For instance:

```
// firestack.js
import Firestack from 'react-native-firestack'

const firestack = new Firestack({});
export default firestack;
```

And import it from another file, i.e.:

```
// some other reducer
import firestack from './firestack'

// ...
```

Hope that helps!

**Comment by neosekar** [comment]
Hi auser thanks for the reply. 
If firestack like above mentioned solution, then firestack debugger shows 
msg: **"FirebaseApp name [DEFAULT] already exists!"** and also I can't use **signInwithEmail** method. In this method response methods not triggers like then or catch method is not executing. 
Can you please help me this ?
