### ISSUE TITLE
 need Storage method to deleteFile()

### ISSUE THREAD

**Issue by abcd-ca** [fullstackreact/react-native-firestack#263]
I believe the method is `deleteWithCompletion` on iOS and `delete` on Android

**Comment by Salakar** [comment]
@abcd-ca check out the v3 branch - much more complete storage implementation there.

**Comment by abcd-ca** [comment]
@Salakar Can you tell me what the status of the FCM is? Should I attempt to use it?

**Comment by abcd-ca** [comment]
Follow-up for anyone that sees this, V3 branch works great and has delete method, I've tried it now.
