### ISSUE TITLE
Support for multiple instances

### ISSUE THREAD

**Issue by Paul-Todd** [fullstackreact/react-native-firestack#266]
Are there any plans to support multiple named instances of Firebase as documented [here](https://firebase.google.com/docs/reference/js/firebase.app.App)

This is useful for the scenario where there is a need to create a new account but not login - see [Stackoverflow](http://stackoverflow.com/a/38013551)

**Comment by Salakar** [comment]
@Paul-Todd eventually yep, but probably not for a while, trying to get what we have currently stable  and the missing features implemented. 

Will close this for now, but it is definitely on the todo. :)
