### ISSUE TITLE
Query with startAt / endAt not working?

### ISSUE THREAD

**Issue by mikesurowiec** [fullstackreact/react-native-firestack#27]
I'm trying to get pagination working in my app, but it appears the startAt / endAt doesn't affect the queries. I'm using it in conjunction with `limitToLast`, I'm not sure if that's an issue.

I was playing with a couple different strategies, so let me see if I can boil it down...

```js
let myRef = firestack.database.ref('chat-messages/roomId');

myRef.orderByKey().limitToLast(10).once('value').then((snapshot) => {
  let itemKeys = Object.keys(snapshot.val());
  let lastItemKey = itemKeys[itemKeys.length-1];

  myRef.orderByKey().startAt(lastItemKey).on('child_added', (data) => {
    if (data.key === lastItemKey) {
      return;
    }
    // This fires for all items in the collection, despite the startAt(lastItemKey)
    console.log('got data', data);
  });
});
```

I'm also pretty new to firebase, so there could just be a logical error in there 😄 

Thanks for you time!

**Comment by auser** [comment]
@mikesurowiec I'll look into it right now. I'm not sure about your specific query, but I'll take a peek!

**Comment by auser** [comment]
@mikesurowiec Confirmed this as a bug and just pushed the fix. Can you try using the master branch, or push an `npm`?

Thanks for reporting!

**Comment by alfian0** [comment]
same, here ...I think is resolved ?but I still got that issue
