### ISSUE TITLE
[v3] Database listener firing and dying instantly on Android

### ISSUE THREAD

**Issue by ultimagriever** [fullstackreact/react-native-firestack#273]
I have a component which keeps listening to Realtime Database changes, as shown below:

```
const { currentUser } = firestack.auth();
firestack.database().ref(`/users/${currentUser.uid}/employees`)
    .on('value', snapshot => {
      dispatch({ type: 'employees_fetch_success', employees: snapshot.val() });
    });
```

My Android Studio emulator log shows the following messages:

```
D/FirestackDBReference: Added ValueEventListener for path: .info/serverTimeOffset with modifiers: 
D/FirestackDBReference: Added ValueEventListener for path: /users/pc6JyqwONnUnZgs5XtK6KtUtsUI3/employees with modifiers: 
D/FirestackDatabase: Removed listener .info/serverTimeOffset/
D/FirestackDatabase: Removed listener /users/pc6JyqwONnUnZgs5XtK6KtUtsUI3/employees/
```

And the data never gets retrieved from the DB.
I don't remove the listener anywhere in the code, the iOS version works fine even on TestFlight. I only get this issue on Android.
The rest of the features (inserts to the DB, authentication) all work. I only have issues with retrieving data.

**Comment by Salakar** [comment]
@ultimagriever someone, no names mentioned, merged something they shouldn't of on v3 branch that broke refs in android, most of us over on gitter are using my fork as its much further ahead and we have control over merges, try installing my fork - https://github.com/Salakar/react-native-firestack.

```
# remove node_modules/react-native-firestack directory from your project
# remove it as a dependency from your package.json

# then install firestack from my fork:
npm install https://github.com/Salakar/react-native-firestack.git --save
```

Should all be working after that, we're using it in Production for android, couple others using ios in prod too.

**Comment by ultimagriever** [comment]
Thanks! 👍 
I'll try it out now.

**Comment by Salakar** [comment]
@ultimagriever awesome! 😺

**Comment by ultimagriever** [comment]
Has #218 been implemented in your fork? I'm getting that while trying to build on iOS. :(

**Comment by Salakar** [comment]
@ultimagriever just did it now for you, let me know if its working, will need to re-install from git again, sorry

**Comment by ultimagriever** [comment]
Hey it worked!

Thanks for your swift action! 💯

**Comment by Salakar** [comment]
@ultimagriever good good!

And no worries, happy to help :)

**Comment by Salakar** [comment]
@ultimagriever also, if you get any more issues with v3 could you create them on my fork, thanks 👍
