### ISSUE TITLE
Database event 'once' does not fire.

### ISSUE THREAD

**Issue by ChristianTucker** [fullstackreact/react-native-firestack#28]
Just going to go ahead and leave this here as I tested a few scenarios using firestack version 2.2.3 and React-native version 0.32.0.

```
firestack.database.ref('...').once(...)
```

Will never fire, however calling

```
firestack.database.ref('...').on(...)
```

and then deregistering the listener works fine. 

EX:

```
var x = firestack.database.ref('users').on('value', (snapshot) => {
            firestack.database.ref('users').off(x)
            // Handle snapshot
}
```

The problem with this is that .off() stops execution, so it must be done at the bottom of the chain, which makes it a mess to do with promises, you have to close the listener in a round-about way.

**Comment by auser** [comment]
Hey @ChristianTucker thanks for the issue.

So, `firestack` is built on promises, so it won't callback a function like the way you have it written there. Instead, it will resolve the promise. For example:

```javascript
firestack.database.ref('users').on('value').then(snapshot => {
            firestack.database.ref('users').off(x)
            // Handle snapshot
});
```

The child syntax does work. What are you trying to do with the child syntax? 

```javascript
database.ref('chat').child('roomId') // executes 
```

**Comment by ChristianTucker** [comment]
@auser, sorry I was in the middle of editing my issue, the `child` problem was my own which is why it was removed (almost immediately before you responded). I'm getting responses with the callbacks (and promises) it doesn't seem to matter which of them I use. Although knowing that promises are the way it was designed, I'll make sure to stick with them. 

The only issue here is the `once` call, sorry about the confusion.  If you test the code you provided, you'll see that calling `off(x)` halts execution, so handling the snapshot below it does not work. This is fine, unless of-course, you're in a promise.

EX:

```
function checkUserExistance(userId) {    
    return new Promise((resolve, reject) => {
        var x = firestack.database.ref('users').child(userId).on('value', (snapshot) => {
            firestack.database.ref('users/'+userId).off(x)
            if(snapshot.val()) return resolve(true)
            return resolve(false)
        }, err => {
            console.warn("Error: " + JSON.stringify(err))
        })
    })
}
```

Will not ever resolve the promise. Resolve also halts execution (Without the return, I just keep it there for best practice and browser compatibility from when I was doing web development) so the process of closing out the listener and handling the data gets extremely confusing.

**Comment by auser** [comment]
Yes, every function in firestack returns a promise, so you can reshape your example to take advantage of that. For instance, you might change your function to:

```javascript
function checkUserExistance(userId) {    
    return firestack.database.ref('users').child(userId)
      .on('value', (snapshot) => {
        return firestack.database.ref('users/'+userId).off('value')
                .then(snapshot => snapshot.val() ? true : false)
                .catch(err => false)
      })
    }
}
```
