### ISSUE TITLE
Compatibility with RN 0.41?

### ISSUE THREAD

**Issue by almadsen** [fullstackreact/react-native-firestack#281]
I'm getting [!] The target `ProjectName-tvOSTests` is declared twice. when linking iOS with react-native link react-native-firestack
Guess this is a bug cause it works fine with RN 0.40
Think it's a relatively easy bug to duplicate for you.

**Comment by SteffeyDev** [comment]
If you edit the pod file and delete the tv os section it works fine.  Unless you are actually making a tvOS app?

**Comment by auser** [comment]
Closing as specific
