### ISSUE TITLE
v3 no longer actively developing?

### ISSUE THREAD

**Issue by IljaDaderko** [fullstackreact/react-native-firestack#306]
Hey guys, seems like progress on v3 slowed down and issues are not being responded to, too well. Wanted to ask if you are no longer planning to keep developing it and what future of firestack looks in general? Appreciate work you've done so far :)

This is the best firebase solution for react-native so far.

**Comment by ajostergaard** [comment]
Perhaps it's no longer true that "the latest version of Firebase requires the window object"?

**Comment by IljaDaderko** [comment]
@ajostergaard no it doesn't, I'm currently using web sdk just fine 👌 firestack is a great tool to bring additional features like analytics / crash reporting etc to the project

**Comment by ajostergaard** [comment]
@IljaDaderko Are those features not available direct via the Firebase APIs? Kind of wondering whether there's any need for Firestack now that Firebase itself is maturing?

**Comment by IljaDaderko** [comment]
@ajostergaard Unfortunately not, things like Analytics for example are only available for iOS and Android (i think Unity as well), but nod within firebase JS sdk.

**Comment by ajostergaard** [comment]
Perhaps time to switch to Firestack - thanks for the clarification!

**Comment by jasan-s** [comment]
plus Facebook & google auth as well storage is not supported

**Comment by ajostergaard** [comment]
Thanks for the clarification guys and sorry @IljaDaderko for hijacking your issue. Your question remains unanswered, will you open another or shall I?

**Comment by gabsn** [comment]
@ajostergaard Maybe you should, I'm also interested by this question.

**Comment by Salakar** [comment]
@ajostergaard @gabsn @jasan-s I was the maintainer/creator of v3 and the majority of the changes were done by myself. 

Have since moved to https://github.com/invertase/react-native-firebase - it's well tested, updated daily, and much more of a complete implementation for both platforms, auth for example is 100% implemented on both platforms.

**Comment by ajostergaard** [comment]
@Salakar good tip - thanks!!!
