### ISSUE TITLE
Database ref.on does not work on Android

### ISSUE THREAD

**Issue by alexkendall** [fullstackreact/react-native-firestack#31]
I have the same exact code on Android and iOS for observing value changes on my database. It works on iOS as expected but does not work on Android. I have placed my code below as a reference: 

```
.ref("shifts")
    .on('value', snapshot => {
    console.log(snapshot)
 })
```

**Comment by auser** [comment]
Are you working on `master` or the npm module?

**Comment by alexkendall** [comment]
I believe so... I installed it using "npm install react-native-firestack --save".

**Comment by auser** [comment]
Hmm... that's the latest... I'll check over here too

**Comment by auser** [comment]
I'm seeing it here too... currently debugging...

**Comment by auser** [comment]
Okay, tracked it down. I should have a fix here shortly

**Comment by alexkendall** [comment]
Cool sounds great.

**Comment by auser** [comment]
@alexkendall got it.

Want to test it on your end?

**Comment by alexkendall** [comment]
Yup. Will be glad to.

**Comment by auser** [comment]
Have one more fix coming...

**Comment by auser** [comment]
Okay, good news and bad news!

Good: It's fixed
Bad: I pushed it to the `feature/messaging` branch. Can you pull and try it from that branch?

**Comment by alexkendall** [comment]
I pulled from the messaging branch and can confirm that the issue is fixed. Thanks a ton!

**Comment by auser** [comment]
@alexkendall awesome! Feel free to report any bugs whenever you encounter one. It _definitely_ helps. 

I hope to get the push notifications/messaging in/complete this weekend!

**Comment by blumanski** [comment]
@auser 
Was that ever merged into the master branch?
I work from the master branch and the problem is till there on android.

**Comment by auser** [comment]
Hmm... yes, I think it is on the master branch. Have a git repo I can check out?

**Comment by blumanski** [comment]
Ah, yeah, I wrote it wrong, I used a promise instead of a callback...
All good, Thanks
