### ISSUE TITLE
Error linking library

### ISSUE THREAD

**Issue by maggialejandro** [fullstackreact/react-native-firestack#310]
Hi, I'm having this issue when running: _react-native link react-native-firestack_

> Scanning 648 folders for symlinks in /var/www/react-native-tc-demo/node_modules (8ms)
> Preparing to link react-native-firestack for iOS
> Checking CocoaPods...
> CocoaPods already installed
> rnpm-install info Linking react-native-firestack android dependency 
> rnpm-install info Android module react-native-firestack has been successfully linked 
> rnpm-install info Linking react-native-firestack ios dependency 
> rnpm-install info iOS module react-native-firestack has been successfully linked 
> Checking Podfile in iOS project (/var/www/react-native-tc-demo/ios/Podfile)
> Adding Podfile to iOS project
> Installing Pods
> node_modules/react-native-firestack/bin/cocoapods.sh: 63: node_modules/react-native-firestack/bin/cocoapods.sh: pod: not found
> /var/www/react-native-tc-demo/node_modules/react-native/local-cli/core/makeCommand.js:29
>         throw new Error(`Error occured during executing "${command}" command`);
>         ^
> 
> Error: Error occured during executing "node_modules/react-native-firestack/bin/cocoapods.sh" command
>     at ChildProcess.prelink (/var/www/react-native-tc-demo/node_modules/react-native/local-cli/core/makeCommand.js:29:15)
>     at emitTwo (events.js:106:13)
>     at ChildProcess.emit (events.js:192:7)
>     at maybeClose (internal/child_process.js:890:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

Aditional Information:
- RN 42
- Firebase 3.7.1
- Platform: Ubuntu 16

**Comment by bramvbilsen** [comment]
I'm also getting an error while linking! This is what my terminal is showing:

> rnpm-install ERR! It seems something went wrong while linking. Error: spawn UNKNOWN
> Please file an issue here: https://github.com/facebook/react-native/issues
> 
> spawn UNKNOWN

Any help would be appreciated :)

**Comment by arabscimitar** [comment]
This is related to these lines in packege.json

    "commands": {
          "prelink": "node_modules/react-native-firestack/bin/prepare.sh",
          "postlink": "node_modules/react-native-firestack/bin/cocoapods.sh"
    },

**Comment by bramvbilsen** [comment]
But I work on my project both on windows 10 and MacOS. Won't I get problems on MacOS if I remove those lines?

**Comment by arabscimitar** [comment]
Not sure about MacOS I tried it on windows 10

**Comment by lobo922** [comment]
I'm also getting 'rnpm-install ERR! It seems something went wrong while linking. Error: spawn UNKNOWN
Please file an issue here: https://github.com/facebook/react-native/issues

spawn UNKNOWN'

and i don't have the lines '"commands": {
      "prelink": "node_modules/react-native-firestack/bin/prepare.sh",
      "postlink": "node_modules/react-native-firestack/bin/cocoapods.sh"
},'
in my package.json

**Comment by arabscimitar** [comment]
these two lines are not in Your packege.json these lines in the firestack package.json

**Comment by lobo922** [comment]
yep, that did the trick
thanks for the tip!
