### ISSUE TITLE
emit events (firestack.analytics.logEventWithName)

### ISSUE THREAD

**Issue by davidgit75** [fullstackreact/react-native-firestack#319]
Hello, I am using this code to send en event and add it to the events list on firebase analytics:

```
const firestack = new Firestack({ debug: true });

firestack.analytics.logEventWithName('init_home', {
      screen: 'home',
    })
    .then(res => console.log('Sent event named launch'))
    .catch(err => console.error('You should never end up here'));
```

And I don't know if I need more configurations, so this code doesn't work os in the firebase console show an image that say `Integrate the SDK and the first event reports are displayed within 24 hours` and I don't know what is bad.`

I made this configuration on one component of my app

```
const firestack = new Firestack({ debug: true });
```

And that's all what I do. Is necessary to add more configurations? I added google-services.json on my android/app directory. Thanks

**Comment by dzuncoi** [comment]
Did you figure it out @davidgit75 ?

**Comment by Salakar** [comment]
@davidgit75 @dzuncoi I don't think this is fully implemented yet here, but there are [alternatives you can use](https://github.com/invertase/react-native-firebase).

**Comment by dzuncoi** [comment]
Yeah @Salakar, I've switched to that lib already.

**Comment by davidgit75** [comment]
Yeah, I solved using only react-native-firebase-analytics

Thanks for help
