### ISSUE TITLE
runtime crash: Symbol not found: _OBJC_CLASS_$_AppDelegate

### ISSUE THREAD

**Issue by mikesurowiec** [fullstackreact/react-native-firestack#32]
Hey there, starting with this commit: d737b3697d11e I'm unable to run my project. I get the following error right after the app launches:

```
dyld: Symbol not found: _OBJC_CLASS_$_AppDelegate
 Referenced from: /Users/michaelsurowiec/Library/Developer/Xcode/DerivedData/Lokel-fyslvyjvsgzbcfeaocpmdtbindow/Build/Products/Debug-iphonesimulator/libFirestack.a
 Expected in: flat namespace
in /Users/michaelsurowiec/Library/Developer/Xcode/DerivedData/Lokel-fyslvyjvsgzbcfeaocpmdtbindow/Build/Products/Debug-iphonesimulator/libFirestack.a
```

**Comment by auser** [comment]
Shoot! I merged a working commit in master. 

I'll take a quick debug look and see if I can track that down. 

I believe the npm module won't do that.

**Comment by mikesurowiec** [comment]
No worries! I didn't realize you had WIP stuff there

**Comment by auser** [comment]
@mikesurowiec Do you have an AppDelegate in your iOS app source?

**Comment by mikesurowiec** [comment]
We do, but it's AppDelegate.swift

**Comment by auser** [comment]
Gotcha. Well, that makes sense as to why that error is happening... 

Can you try adding the @obj attribute to the class (https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html) and see if that fixes it for you?

**Comment by auser** [comment]
Fixed.
