### ISSUE TITLE
FirebaseApp with name [DEFAULT] doesn't exist

### ISSUE THREAD

**Issue by blumanski** [fullstackreact/react-native-firestack#33]
After I added the code below to the android manifest (Readme File), I got the error "FirebaseApp with name [DEFAULT] doesn't exist".

I guess you added that recently with some upgrades to the android messaging.
Anyway, it is not a problem, after removing it was running again.

I assume this will come with the next npm release?

    +   <service android:name="io.fullstack.firestack.FirestackMessagingService">
    +     <intent-filter>
    +       <action android:name="com.google.firebase.MESSAGING_EVENT"/>
    +      </intent-filter>
    +   </service>

**Comment by auser** [comment]
Yes, I'm working off master. We'll definitely need to address messaging soon. 

The warning shouldn't be an issue... did that happen off the first load or follow-ups?

**Comment by blumanski** [comment]
In the logs in Android Studio I had the message that "io.fullstack.firestack.FirestackMessagingService" cant be found or something like that.

And on the device, using "react-native run-android" I got the "FirebaseApp with name [DEFAULT]"
So, nothing to be concerned, I thought, I just mention it in case somebody jumps now on and is getting that error.
Great work and Thanks
