### ISSUE TITLE
How to use with redux?

### ISSUE THREAD

**Issue by tarkanlar** [fullstackreact/react-native-firestack#34]
I am trying to add this library to my react native app. I successfully set it up but how can I properly make it work with redux? In `read me` it says there is FirestackModule but can anyone explain better how to implement with redux?

**Comment by auser** [comment]
Hey @tarkanlar,

Thanks for leaving this question! Yes, I can describe it better for you. Basically, the FirestackModule is an interface between Firestack and Redux. I have a TODO to fill out the docs for the FirestackModule. If you're interested in more depth, I can hop on gitter and walk through it... it would be a good way for me to start documenting the module.

**Comment by tarkanlar** [comment]
@auser  Thanks for your reply,  I pulled and checked your FirestackApp repo it is a great source but I am confused in a few parts of the code. Anyway I will ask on gitter.

**Comment by ajonno** [comment]
hey Ari, hope your well. I need to integrate Firestack to Redux to ensure a single instance only (of Firestack) is passed around the app. Keen to get this done via Redux but need some help/guidance. Can you please assist ? (I looked through the FirestackApp code but some of it I didnt understand / re how to use in our current app).

**Comment by auser** [comment]
Sure! Will you be online tonight?

Get Outlook for iOS




On Wed, Mar 1, 2017 at 8:43 PM -0800, "Angus Johnston" <notifications@github.com> wrote:












hey Ari, hope your well. I need to integrate Firestack to Redux to ensure a single instance only (of Firestack) is passed around the app. Keen to get this done via Redux but need some help/guidance. Can you please assist ? (I looked through the FirestackApp code but some of it I didnt understand / re how to use in our current app).

**Comment by ajonno** [comment]
Hi Ari, 

Unf. im out tonight but can do tomorrow. Also in the mean time I’ve wired up a singleton which is working fine. I’d still like to better understand how to bring Firestack into Redux however so still keen to go through that. I’ll message you tomorrow my time, say around 6pm

 

Cheers

angus

**Comment by Reminouche** [comment]
Hi Ari,

First or all, thanks for your work.
I think it will probably be better to create a documentation for that. I am interested too by a firestack integration with redux.

**Comment by Reminouche** [comment]
Any news about this ? @auser
