### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by blumanski** [fullstackreact/react-native-firestack#35]
I know, this is still in progress. 
I am testing a bit at the moment and noticed some stuff.

On IOS the code below works fine, it is getting data and is updating data on change.
The same code does not work on android yet.

    _this = this
            this.props.FirebaseStack.database.ref('chat/Zeitkapsel/messages').on('value', function(snapshot) {
                _this.setState({
                    dataSource: _this.state.dataSource.cloneWithRows(snapshot.value),
                    animating: false
                });
            })

On android, the code below works, so, "once" works

           _this = this;

            this.props.FirebaseStack.database.ref('chat/Zeitkapsel/messages').once('value')
                .then(function(snapshot){
                    _this.setState({
                      dataSource: _this.state.dataSource.cloneWithRows(snapshot.value),
                      animating: false
                    });
                })
                .catch(function(error){
                    console.log(error);
                })

**Comment by auser** [comment]
Oh yikes! I'll check that shortly. Thanks for reporting!

**Comment by blumanski** [comment]
It seems just to load and the callback never finish, no error message either.
Thanks for looking

**Comment by auser** [comment]
Hmm... I can't replicate it... it's working here... Are you using the `npm` version or the github version? @blumanski

**Comment by blumanski** [comment]
I am using the npm version, I will retest it tomorrow, may it's another problem.
I may will upgrade master branch and see how that goes.

Thanks @auser

**Comment by auser** [comment]
Awesome @blumanski 

I believe the npm and github version are much different than each other. I'll tag the next release

**Comment by blumanski** [comment]
@auser 
I just tried it using the master branch instead of the npm version.
It works fine.

I did run into some IOS build trouble, I will try again to get it run and let you know.
Cheers

**Comment by auser** [comment]
Did you figure out the iOS build issue?

Get Outlook for iOS




On Sun, Sep 25, 2016 at 5:26 PM -0700, "Oliver Blum" <notifications@github.com> wrote:












Closed #35.
