### ISSUE TITLE
Invalid Swift Support error occurs when deploying App to the Appstore

### ISSUE THREAD

**Issue by IjzerenHein** [fullstackreact/react-native-firestack#39]
Hi,

I've reached the point where I am deploying the App to the iOS app-store, but the app is being rejected because of the following error:

```
Invalid Swift Support - The SwiftSupport folder is missing.
Rebuild your app using the current public (GM) version of Xcode and resubmit it.
```

After some investigating and disabling libraries I found that this happens when including firestack. After removing firestack using `react-native unlink react-native-firestack` the problem disappears.

Has anyone already ran into this, any solutions?

thanks,
Hein

**Comment by tarkanlar** [comment]
Hi I haven't deploy yet but when I tried to integrate ```https://github.com/fullstackreact/react-native-oauth``` I have seen the same error and removed oauth

**Comment by auser** [comment]
Yes, the auth library requires swift... I think I need to update the README as I haven't touched react-native-oauth in a little bit.

**Comment by IjzerenHein** [comment]
Why has this been closed? I'm not using oauth in any way in my app, nevertheless the deploy to the app store is failing.
Should I change something in my app to resolve this?!

**Comment by auser** [comment]
What is the error, @ljzerenHein? Is it still giving you the same trouble without `react-native-oauth`?

**Comment by IjzerenHein** [comment]
Yes, I'm not using `react-native-oauth`. I merely included `react-native-firestack` in my app and am only using the Storage functionality of that.

**Comment by auser** [comment]
@ljzerenHein. Okay, lemme check it here.

**Comment by IjzerenHein** [comment]
Awesome, thanks @auser

**Comment by auser** [comment]
Update: I'm able to replicate this. Hunting it down now.

**Comment by DVassilev** [comment]
Can confirm I received the same issue. Glad to see it being resolved!

**Comment by auser** [comment]
I resolved this the simplest way... 

I have _not_ pushed the update to `npm` yet (I want to make sure it works for everyone and update the README). Please, update your libraries and run this command:

`rnpm unlink react-native-firestack && react-native link react-native-firestack`

It will create a Podfile for you and install the dependencies, if you don't already have one.

**Comment by IjzerenHein** [comment]
Alright cool, I'll hopefully get around testing this soon. I'll keep you posted
