### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by shraddha1704** [fullstackreact/react-native-firestack#4]
This is a great module! When can we expect android support?

**Comment by cihancil** [comment]
I am about to start a project. I will need Android support. Is it possible we get Android in 1-2 months?

**Comment by auser** [comment]
@cihancil It's possible. I'm currently working on documentation for this module, so when I'm done with the post, I'm hoping to get to Android support, unless the community wants to jump in and help. 

This is definitely a HIGH priority.

**Comment by cihancil** [comment]
Firebase team announced that their JavaScript SDK now works with React Native. Might be better to focusing the parts that they don't support. For example their storage service.

**Comment by auser** [comment]
I know. I've read through much of the source and am using it with this project. This library is really to serve as a shim to cover the stuff their JS library doesn't cover/support. The parts that DO work in the JS library are simple pass-throughs to their JS library.

**Comment by amelekesov** [comment]
+1

**Comment by Roman-K93** [comment]
+1

**Comment by PylypchukKhrystyna** [comment]
+1

**Comment by SunaNoOshiro** [comment]
+1

**Comment by praneybehl** [comment]
+1

**Comment by alvirtuoso** [comment]
+1

**Comment by g6ling** [comment]
I made [react-native-firebase-auth-android](https://github.com/g6ling/react-native-firebase-auth-android) which only support firebase auth. But you want to use firebase database, you can use firebase js version. And you want to add social Login with firebase, read this post.[How to add Firebase auth with react-native](https://github.com/g6ling/How-to-add-Firebase-Auth-with-react-native)

**Comment by praneybehl** [comment]
Hi checking in since I am starting a new project that needs Android support. 
How it is coming along? 
Cheers

**Comment by auser** [comment]
@praneybehl We're just getting start it on it. @g6ling seems to have a pretty good handle on it in his library. @g6ling Interested in collaborating and adding Android support together?

**Comment by praneybehl** [comment]
Thanks for the info. I would love to help but my knowledge with Java is close to none. I work with javascript, so if there is anything I can help with, I would love to.

Cheers!

**Comment by candicom** [comment]
+ 1

**Comment by g6ling** [comment]
@auser yes. I'm interested in this library. I want to collaborate this project(Android version) with your team. What can i do for this project?

**Comment by auser** [comment]
@g6ling Awesome. I know you've done some initial work with your repo on adding auth. The JS interface is pretty intentionally thin right now, so perhaps we can integrate some of your Android work to cover the auth API?

**Comment by auser** [comment]
Holla all.

Okay, I pushed a _very_ basic, incomplete Android version based almost entirely on @g6ling's work. Although it's not complete, it's a start.

**Comment by auser** [comment]
One more update: I added some notes to the android features with the rest of the JS api. Feel free to fill in the blanks. Should just be pretty easy to look in the Firebase docs and copy + paste the implementation.

**Comment by auser** [comment]
Android support is built-in and starting to be baked in. If you're interested in contributing, it's broken out into modules now and should be very straightforward.

**Comment by praneybehl** [comment]
Great work, Is there a list of what is currently available for Android?

**Comment by auser** [comment]
Thanks. 

My tests show that auth is working on android. I confirmed file uploading works as well. The database has partial support (have a few remaining pieces of code to complete, but the logs show exactly what). 

Off the top of my head, the rest still needs some work, but I can look deeper when I get to a keyboard.

**Comment by auser** [comment]
Okay, I've updated quite a bit of the Android API. Storage, Analytics are complete. 

Auth still needs some providers work (2 methods)
Database needs to add `off()` and `removeListeners()`

Otherwise everything else should be covered.

**Comment by praneybehl** [comment]
@auser this is awesome, I am hoping these will be ready soon. So if someone was to start dev, what would you say wait or get started as it's coming real soon.

Really appreciate your work here  👍 💯 

Cheers

**Comment by auser** [comment]
@praneybehl Hey, thanks for the comment. Yeah, definitely get started. I aim to help support your app with features. Plus, it can help discover any bugs/features as you're building. Feel free to join the gittr room if you want to discuss more.

Cheers!

**Comment by praneybehl** [comment]
@auser Thanks mate, I will now. Is there a link to the Gittr room?

**Comment by auser** [comment]
Here ya go: [gitter](https://gitter.im/fullstackreact/react-native-firestack)

I'll update the README if it's not there already.

**Comment by praneybehl** [comment]
Thanks mate just joined

**Comment by auser** [comment]
We have parity in coverage now.

Social auth have yet to be implemented (mostly due to time)
