### ISSUE TITLE
Build IOS errors

### ISSUE THREAD

**Issue by blumanski** [fullstackreact/react-native-firestack#40]
Using the master branch, I get the following errors on build/run.
I followed the readme, it is working fine on Android.
I guess something is not linked, google service ugraded?

Thanks

Xcode Error Messages

    node_modules/react-native-firestack/ios/Firestack/FirestackCloudMessaging.m:102:3: 
    Use of undeclared identifier 'UNAuthorizationOptions'

    node_modules/react-native-firestack/ios/Firestack/FirestackCloudMessaging.m:106:5:
    Unknown receiver 'UNUserNotificationCenter'; did you mean 'NSNotificationCenter'?

React-Native Errors

    CompileC ios/build/Build/Intermediates/Firestack.build/Debug-iphonesimulat/Firestack.build
    /Objects-normal/x86_64/FirestackCloudMessaging.o  
    Firestack/FirestackCloudMessaging.m  normal x86_64 objective-c
    com.apple.compilers.llvm.clang.1_0.compiler

**Comment by blumanski** [comment]
Ok, could that be the ios emulator, it's probably not running on the emulator I can imagine.

**Comment by auser** [comment]
Mmm the cloud messaging isn't fully implemented yet, so I am not quite sure yet on its implementation. 

Have any experience with cloud messaging? I'm not convinced yet with its api. Have any interest in sketching a JS implementation together?

**Comment by auser** [comment]
And yes, I upgraded all packages with the last push

**Comment by blumanski** [comment]
I just had a quick look, it looks already good, this below was working fine on android. But that was the only thing I tested quickly.

    this.props.FirebaseStack.cloudMessaging.getToken().then(function(token) {
        console.log(token);
    })

I am happy to test it and see what I can do.

Regarding the built error in IOS, I couldn't get that running and focus right now more on android. Nothing in a hurry.

Cheers

**Comment by slycoder** [comment]
I think this was fixed with #38

**Comment by blumanski** [comment]
Yes, all good
