### ISSUE TITLE
logEventWithName error

### ISSUE THREAD

**Issue by vico-aguado** [fullstackreact/react-native-firestack#42]
When I try to use Analytics, I get this error: 

 

> firestack.logEventWithName is not a function

I have: 
```
firestack.logEventWithName("launch", {
      'screen': 'Main screen'
    })
    .then(res => console.log('Sent event named launch'))
    .catch(err => console.log('You should never end up here'));
```

In fact I login and retrieve info from Firebase with success

**Comment by auser** [comment]
Oh... the docs need to be updated. 

It's now: `firestack.analytics.logEventWithName()`. Apologies for the inconvenience!
