### ISSUE TITLE
Which part of the API is not available on Android ?

### ISSUE THREAD

**Issue by nelsonkam** [fullstackreact/react-native-firestack#43]
The documentation in the README file states that:

> Full Android support is coming soon, as it currently supports a smaller feature-set than the iOS version

But doesn't precise which feature-set is supported or not by Android.

**Comment by auser** [comment]
Good question! I'll update the README. with coverage details.

(traveling today, so I'll add this while in flight). We're _mostly_ completely covered between the two platforms.

**Comment by nelsonkam** [comment]
Thanks for your attention. Have a nice trip :wink:. Cheers !

**Comment by Catuna** [comment]
@auser Any ETA on when this will be done?

We would really like to use Firestack in our project but we need to know what is missing from Android :)

**Comment by rchrdschfr** [comment]
@auser Also really need to know what's missing from Android

**Comment by auser** [comment]
Yes -- we are actually pretty close to covering everything. I'll make a chart and update the README with it, but auth/analytics/database/storage/presence are all complete on the Android side. 

Although I haven't tested it myself, messaging is in for Android as well.

**Comment by rchrdschfr** [comment]
Thanks @auser. I just tested sending upstream messages on Android successfully. Using the old send() though, as sendMessage() doesn't appear to be implemented for Android yet.

**Comment by auser** [comment]
Is this the messaging api?

Get Outlook for iOS




On Mon, Oct 3, 2016 at 10:08 PM -0700, "Richard Schaefer" <notifications@github.com> wrote:












Thanks @auser. I just tested sending upstream messages on Android successfully. Using the old send() though, as sendMessage() doesn't appear to be implemented for Android yet.

**Comment by rchrdschfr** [comment]
Yes, the cloudMessaging API

**Comment by rchrdschfr** [comment]
I get 

`[TypeError: undefined is not an object (evaluating '(_ref=typeof fn==='function'?fn:NativeModule[fn]).call')]`

When attempting to call sendMessage() on Android. send() works as expected, though.

**Comment by auser** [comment]
@rchrdschfr I actually did not implement the cloudMessaging API so I'm a tad less familiar with it. I'll set this as higher priority and check that tonight.
