### ISSUE TITLE
setStoragetUrl

### ISSUE THREAD

**Issue by blumanski** [fullstackreact/react-native-firestack#45]
Not really an issue, readme update needed, the gs:// is automatically added.

does not work

    firestack.storage.setStorageUrl(`gs://${config.firebase.storageBucket}`)

does work

    firestack.storage.setStorageUrl(`${config.firebase.storageBucket}`)

**Comment by auser** [comment]
@blumanski want to make a PR?

**Comment by blumanski** [comment]
done
