### ISSUE TITLE
How to download file from the bucket

### ISSUE THREAD

**Issue by alanhoff** [fullstackreact/react-native-firestack#49]
Hey there, I'm using iOS and the latest version of Firestack. Is there a way to download a file from the bucket instead of only generating the URL?

**Comment by auser** [comment]
As of right now, not yet -- but should be pretty easy to implement. 

Android: https://firebase.google.com/docs/storage/android/download-files
iOS: https://firebase.google.com/docs/storage/ios/download-files

Feel free to fork and add, if you're interested in getting a PR in. I'll try to get to this this weekend.

**Comment by alanhoff** [comment]
My iOS skills are awful, but it would be great to have this feat. Let me know if you need help with testing :-)

**Comment by alanhoff** [comment]
@auser actually I'll try to implement the download stuff this week, but feel free to implement it if I don't PR until the weekend :-)

**Comment by auser** [comment]
Oh awesome! Should be too hard. Feel free to jump in the gitter room if you have any questions. I try to stay active in there.

**Comment by auser** [comment]
Hopefully the source for both android and iOS is understandable. I'm working on a test harness as well, so soon it should be even clearer.

**Comment by auser** [comment]
This has been merged :)
