### ISSUE TITLE
How to remove unused dependencies?

### ISSUE THREAD

**Issue by miclaus** [fullstackreact/react-native-firestack#54]
If I don't need e.g. `FirebaseAuth`, how can I remove unused Pods dependencies?

Currently I commented out FirebaseAuth in my `Podfile` and rerun `pod install`, which removed FirebaseAuth, however Xcode throws me the following error:

<img width="260" alt="screen shot 2016-10-06 at 20 15 48" src="https://cloud.githubusercontent.com/assets/4658706/19164798/bdb1d64e-8c01-11e6-8dcc-919fdbbbb80b.png">

Please help :) Thank you !

**Comment by auser** [comment]
Hey!

I'll push a fix for that to master in an hour for that bug. Apologies!

I'll close this if it's solved for you.

**Comment by auser** [comment]
@miclaus Can you try with the latest master branch?

**Comment by miclaus** [comment]
@auser sure can do. I did try it with the current master branch.

Just for the record, here's my `Podfile`:

```rb
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

[
  'Firebase',
  #'Firebase/Core',
  #'Firebase/Auth',
  #'Firebase/Storage',
  'Firebase/Database',
  #'Firebase/RemoteConfig',
  #'Firebase/Messaging'
].each do |lib|
  pod lib
end

```

**Comment by miclaus** [comment]
I'll give it another try later today.

**Comment by auser** [comment]
I confirmed it works over here with your same podfile. I'll assume it's working over there and close this issue for now. Feel free to reopen.

**Comment by miclaus** [comment]
@auser I pulled the latest master commit and ran `pod install` and I get a bunch (20) errors:

<img width="415" alt="screen shot 2016-10-14 at 12 01 11" src="https://cloud.githubusercontent.com/assets/4658706/19383691/0581bcd2-9206-11e6-98d4-974b4f620839.png">

I'm not sure whether I'm doing it right..
What are the steps that I have to do after pulling a new version? 

Thank you for your patience ! :)

**Comment by auser** [comment]
Are you opening the `.xcworkspace`?

**Comment by miclaus** [comment]
Yes, but let my try again.

**Comment by miclaus** [comment]
@auser Yes I can confirm.

**Comment by auser** [comment]
hm... I have a deadline I'm working towards right now on a talk I'll be giving in ~5 hours or so. Mind if I ask you to hold tight for a few more hours?

**Comment by miclaus** [comment]
@auser sure no problem! Thanks for your quick response and your help. We really appreciate it.

P.S.: Good luck for your talk !

**Comment by miclaus** [comment]
Here are the steps that I tried (maybe this illuminates the problem) :
- removed `Firestack.xcodeproj` from Libraries
- removed `react-native-firestack`from node_modules
- ran `npm install` from root directory (I use the latest commit e754101)
- removed `Podfile.lock`
- ran `pod install` from ios directory
- opened my project's `.xcworkspace`
- manually linked Firestack according to your guide

**Note** that in my `Linked Binaries` section, after running `pod install`, the `libPods-projectName.a` Binary appeared.

There are **no more errors**, however I get warnings for the exact same modules that I commented out in my `Podfile`:

<img width="853" alt="screen shot 2016-10-14 at 12 48 07" src="https://cloud.githubusercontent.com/assets/4658706/19384951/828c43ea-920c-11e6-995d-620f9fff6683.png">

Here are also my `Build Settings` of the `Firestack.xcodeproj`:

<img width="1048" alt="screen shot 2016-10-14 at 12 35 16" src="https://cloud.githubusercontent.com/assets/4658706/19384716/028c99b6-920b-11e6-8ce3-5d2bd13ac4fd.png">

**Comment by miclaus** [comment]
@auser have you had some time to take a look at this issue ?
