### ISSUE TITLE
unable to build in XCode. No visible @interface for 'FIRMessaging' declares the selector 'setRemoteMessageDelegate:'

### ISSUE THREAD

**Issue by ajonno** [fullstackreact/react-native-firestack#55]
am seeing this error after following ios install steps and trying to run XCode project directly :-

No visible @interface for 'FIRMessaging' declares the selector 'setRemoteMessageDelegate:'

XCode Version 8.0 (8A218a)
deployment target: 8.0
"react": "15.3.2",
"react-native": "0.34.1",
"react-native-firestack": "^2.3.0"

**Comment by auser** [comment]
I'll update the readme to fix this. 

`(cd ios && pod update --verbose)`

**Comment by ajonno** [comment]
great thanks!

**Comment by yn5** [comment]
@auser Could you still update the README? I ran into the same problem and it took me a while to get here.

**Comment by yn5** [comment]
@auser In case this meets your intentions for amending the README: https://github.com/fullstackreact/react-native-firestack/pull/88
