### ISSUE TITLE
No callback to handle database_error event

### ISSUE THREAD

**Issue by chrisbianca** [fullstackreact/react-native-firestack#57]
I've just been trying to get Firestack set up on a brand new project using the FirestackModule and have found an issue when a database permission error is thrown on iOS.

In database.js, a native success and error listener are added for "database_event" and "database_error".  However, in FirestackDatabase.m, both the database events and errors are sent with the "database_event" identifier.

This means that an error is subsequently thrown in database.js as there is no callback registered against a "database_error" type.

I'm happy to submit a PR to make sure that FirestackDatabase.m sends the event as "database_error" but wanted to check there wasn't a reason they're currently sent with the same type before I did?

I'm assuming it's an oversight as the Java code appears to emit the two events separately.

**Comment by chrisbianca** [comment]
Added PR https://github.com/fullstackreact/react-native-firestack/pull/58 as one way of fixing this issue

**Comment by auser** [comment]
Awesome! Thanks for the PR. Good spot.
