### ISSUE TITLE
iOS build failed with Xcode 8.0

### ISSUE THREAD

**Issue by jsappme** [fullstackreact/react-native-firestack#59]
I followed the whole instruction process but it's giving me weird errors while building the project:

any idea why?

Undefined symbols for architecture arm64:
  "___cxa_guard_release", referenced from:
      cachedSystemFont(double, double) in libReact.a(RCTFont.o)
  "std::terminate()", referenced from:
      ___clang_call_terminate in libReact.a(RCTJSCExecutor.o)
  "std::__1::mutex::lock()", referenced from:
      -[RCTModuleData setUpInstanceAndBridge] in libReact.a(RCTModuleData.o)
      cachedSystemFont(double, double) in libReact.a(RCTFont.o)
  "std::__1::mutex::unlock()", referenced from:
      -[RCTModuleData setUpInstanceAndBridge] in libReact.a(RCTModuleData.o)
      cachedSystemFont(double, double) in libReact.a(RCTFont.o)

**Comment by jsappme** [comment]
Here is the end of my errors:

  "operator delete[](void*)", referenced from:
      -[RCTJSCExecutor dealloc] in libReact.a(RCTJSCExecutor.o)
      executeRandomAccessModule(RCTJSCExecutor*, unsigned int, unsigned long, unsigned long) in libReact.a(RCTJSCExecutor.o)
      readRAMBundle(std::__1::unique_ptr<__sFILE, int (*)(__sFILE*)>, RandomAccessBundleData&) in libReact.a(RCTJSCExecutor.o)
      RandomAccessBundleData::~RandomAccessBundleData() in libReact.a(RCTJSCExecutor.o)
  "___gxx_personality_v0", referenced from:
      -[RCTJavaScriptContext initWithJSContext:onThread:] in libReact.a(RCTJSCExecutor.o)
      -[RCTJavaScriptContext init] in libReact.a(RCTJSCExecutor.o)
      -[RCTJavaScriptContext invalidate] in libReact.a(RCTJSCExecutor.o)
      +[RCTJSCExecutor runRunLoopThread] in libReact.a(RCTJSCExecutor.o)
      -[RCTJSCExecutor setBridge:] in libReact.a(RCTJSCExecutor.o)
      -[RCTJSCExecutor init] in libReact.a(RCTJSCExecutor.o)
      -[RCTJSCExecutor initWithUseCustomJSCLibrary:] in libReact.a(RCTJSCExecutor.o)
      ...
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I have those building errors even with a brand new react native project.

**Comment by auser** [comment]
Yeah, try adding the flag: `-lc++` to your target in OTHER_LDFLAGS (other linker flags).

**Comment by jsappme** [comment]
Yes I have those for other linker flags: $(inherited) -ObjC -lc++

**Comment by jsappme** [comment]
I have a solution to my issue. I added -lc++ to the Project (Not Target) Settings > Other Linker Flags

**Comment by gemfile** [comment]
It seems like the same issue in the link below.
https://github.com/facebook/react-native/issues/8890

**Comment by auser** [comment]
Yes, this is a react-native issue, _not_ a firestack issue.
