### ISSUE TITLE
dyld: Library not loaded

### ISSUE THREAD

**Issue by linuxing3** [fullstackreact/react-native-firestack#7]
Got  error loading library with Xcode 7.3.1, which has no `Embed Framework`
Any ideas of solving this?

```
dyld: Library not loaded: @rpath/libFirestack.a
  Referenced from: /var/mobile/Containers/Bundle/Application/40EE0D26-A842-4DF5-BD70-6BC020A7F7E4/rnStartKit.app/rnStartKit
  Reason: image not found
```

**Comment by auser** [comment]
@linuxing3 can you add a build phase to copy the `Embed Framework`?

**Comment by linuxing3** [comment]
Thanks for answering!

I follow this article [announcing](https://www.fullstackreact.com/articles/announcing-firestack-for-firebase/) and add `libFirestack.a` as `new copy file phase` to the project and no errors shown again.

I downloaded the google-service-info.plist and compiled successfully the project to install on my iphone device. 

But when I tried to use the config to create a FireStack Instance, error shows that 

> The default app has not been configured yet.


the config file 
```
// config.js
module.exports = {
  NAME: 'XXXX',
  firestack: {
    apiKey: "XXXXXXXX",
    authDomain: "your-auth-domain.firebaseapp.com",
    databaseURL: "https://your-database-url.firebaseio.com",
    storageBucket: "your-storage-bucket.appspot.com",
  }
}
```

the implementation
```
//src/services/FireStack.js
import Firestack from 'react-native-firestack';
const firestack = new Firestack(config);
```

I thought that all `firebase` frameworks already included in `firestack` and no need to modify `appdelegate.m`. Either the plist file or the config.js should be ok to create a instance of `Firestack`. Don't understand why failed.

**Comment by auser** [comment]
Hmm... are you using `npm` or the branch?

**Comment by linuxing3** [comment]
using `npm  i  react-native-firestack firebase`

**Comment by auser** [comment]
Ah, yes... the latest version of firebase (not yet released, 'cause Android support isn't quite finished... although I might just merge it and release an update) automatically calls `configure()`. I'll update the npm module.

**Comment by auser** [comment]
Can you grab the latest `npm` module (`v2.0.0`) and lemme know if you still see the error?

**Comment by linuxing3** [comment]
That will be great, thanks! I will give it a try.

**Comment by auser** [comment]
Oh and I'm in the gittr chat room if you want to chat in there: https://gitter.im/fullstackreact/react-native-firestack
