### ISSUE TITLE
Error - 'Firebase.h' file not found

### ISSUE THREAD

**Issue by yogieputra8** [fullstackreact/react-native-firestack#72]
I tried to buid with react-native run-ios for the first time and it gives me error:
[![Screen Shot 2016-10-13 at 4.51.20 PM.png](https://s3.postimg.org/i87n6y883/Screen_Shot_2016_10_13_at_4_51_20_PM.png)](https://postimg.org/image/olwqa7d3z/)

here's my package.json:
```
{
  "name": "firestackApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "firebase": "^3.4.1",
    "react": "15.3.2",
    "react-native": "0.35.0",
    "react-native-firestack": "^2.3.0"
  },
  "jest": {
    "preset": "jest-react-native"
  },
  "devDependencies": {
    "babel-jest": "16.0.0",
    "babel-preset-react-native": "1.9.0",
    "jest": "16.0.1",
    "jest-react-native": "16.0.0",
    "react-test-renderer": "15.3.2"
  }
}
```
Can you guys help me how to solve this issue?

**Comment by auser** [comment]
This has been fixed in master. I'll cut a new release.

**Comment by Talkwondo** [comment]
Hi,
Can you explain what you say? i have the same problem too.

Thanks,

**Comment by OrenElad** [comment]
Still have this issue on v ^2.3.2

**Comment by yogieputra8** [comment]
I tried to setup from the beginning and it works. Try these details steps:
1. Do `react-native init your_app`
2. Do `npm install firebase --save` inside your_app folder
3. Do `npm install react-native-firestack --save`
4. Do ` react-native link react-native-firestack`. 
5. Inside ios folder in your project folder check your Podfile, edit your Podfile to be like these:
```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'firestack_app' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for firestack_app
  [
    'Firebase/Core',
    'Firebase/Auth',
    'Firebase/Storage',
    'Firebase/Database',
    'Firebase/RemoteConfig',
    'Firebase/Messaging'
  ].each do |lib|
    pod lib
  end

end
```
6. Do `pod install` from your terminal, and make sure everythings going well in this step.

**------- Setup Firebase ------**
7. Setup your firebase, **Add Firebase to your iOS app**, Make sure your **iOS bundle ID** is same with your **iOS bundle ID** from XCode.
8. Download your **GoogleService-Info.plist** file

**------ Setup your XCode -------**
9. Close your XCode project.
10. Check `your_app folder/ios/ `, you will find file `your_app.xcworkspace`. Open it. From now on, use this file to setup your xcode project.
11. Drag and drop your **GoogleService-Info.plist** file to your XCode project (See image below)
[![687474703a2f2f642e70722f692f31654765762e706e67.png](https://s11.postimg.org/bq06u7mqr/687474703a2f2f642e70722f692f31654765762e706e67.png)](https://postimg.org/image/61tw3bie7/)
12. Save everything and close your XCode.
13. Now you can work from React Native project. (See this Usage Docs [Usage Docs](https://github.com/fullstackreact/react-native-firestack#usage) )






**NB:** I'm using MacOS
