### ISSUE TITLE
signInWithEmail just hangs on android

### ISSUE THREAD

**Issue by sammy6464** [fullstackreact/react-native-firestack#76]
Hi,
I have a project which is setup to work indentically on ios and android, and so far firestack is working for database methods e.g set, however when I go to call signInWithEmail it works perfectly on ios, but just hangs and hangs on android, and my computer starts humming from the cpu going crazy I guess...
There's no feedback in the console nothing changes it would just go on and on if I dont stop the simulator.

Edit: Just to add the database operations are connecting fine on the android version

**Comment by sammy6464** [comment]
Just to add the database operations are connecting fine on the android version

**Comment by auser** [comment]
Thanks for the report. I'll check into this this weekend!

**Comment by sammy6464** [comment]
Great thanks Ari

**Comment by sammy6464** [comment]
OK so this was due to my google play services in the emulator. If anyone else is having this issue make sure to update your google play services.

**Comment by studiobrain** [comment]
@SamMatthewsIsACommonName how did you go about updating your google play services?  Are you referring to the classpath inside android/build.gradle or the dependencies inside android/app/build.gradle?  I am having the same issue via Genymotion emulator.

**Comment by studiobrain** [comment]
^ per my gibberish above:
https://www.genymotion.com/help/desktop/faq/#google-play-services
