### ISSUE TITLE
Incorrect documentation for updateUserPassword

### ISSUE THREAD

**Issue by chrisbianca** [fullstackreact/react-native-firestack#93]
The documentation states that to update a user's password you should call the method updateUserPassword.  However, the method is actually called updatePassword.

Happy to submit a PR.  Should I correct the documentation, or update the name of the method?

The other update methods seems to follow the updateUserXXX convention...

**Comment by auser** [comment]
Yes, please submit a PR.

**Comment by Ehesp** [comment]
https://github.com/fullstackreact/react-native-firestack/issues/118

**Comment by auser** [comment]
Tracking on #118
